[bufix-2.0.x latest] SWITCHING_NOZZLE Marlin\src\module\tool_change.cpp compile error
MarlinFirmware/Marlin pull request #11657
Opened 2018-08-27 14:52 UTC by scott0122

#11632 SWITCHING_NOZZLE  compile error

2018-08-27 22:17 UTC, thinkyhead requested changes
Some changes needed. But I can do that…

2018-08-27 22:17 UTC, thinkyhead commented on Marlin/src/module/tool_change.cpp
> +            current_position[Z_AXIS] += ( (zdiff > 0.0 ? 0.0 : -zdiff) + settings.switching_nozzle_raise_hotend );
No such thing as `settings.switching_nozzle_raise_hotend` in Marlin at this time.

2018-08-28 02:24 UTC, Chuangxiang3D approved these changes
All's good now.

2018-08-28 02:25 UTC, thinkyhead approved these changes

2018-08-28 02:25 UTC, merged

2018-08-28 05:48 UTC, scott0122 commented
Oops...
line 436 to 439 should delete since line 429 already add zdiff

old zdiff code
const float zdiff = hotend_offset[Z_AXIS][**active_extruder**] - hotend_offset[Z_AXIS][**tmp_extruder**];

new zdiff code
zdiff = hotend_offset[Z_AXIS][**tmp_extruder**] - hotend_offset[Z_AXIS][**active_extruder**];

so zdiff is reversed

line 429
`          current_position[Z_AXIS] += zdiff;`

line 436 to 439
`        #if ENABLED(SWITCHING_NOZZLE)`
`          // The newly-selected extruder Z is actually at...`
`          current_position[Z_AXIS] -= zdiff;`
`        #endif`

2018-08-30 21:40 UTC, thinkyhead commented
Everything should now be consistent @scott0122 — Please confirm.