Independent X2-axis StallGuard threshold for IDEX configuration
MarlinFirmware/Marlin pull request #15042
Opened 2019-08-24 13:50 UTC by AlexandrZloy

### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

### Benefits

This fix is for DUAL_X_CARRIAGE printers with TMC2130 drivers and sensorless homing on both X-axises. Added the support of the independent X2-axis StallGuard2 threshold configuration via Configuration_adv.h and lcd-menu.

### Related Issues

Faced this problem on my own DIY printer.

2019-08-24 18:00 UTC, teemuatlut requested changes
Looks like `M914` already supports setting unique SGT values so this essentially extends the support to hard coded defaults and with EEPROM support for it.

2019-08-24 18:00 UTC, teemuatlut commented on Marlin/Configuration_adv.h
> +    #if ENABLED(DUAL_X_CARRIAGE)
I don't think this needs to be behind a feature condition like this. None of the other parameters are.

2019-08-24 18:00 UTC, teemuatlut commented on Marlin/src/inc/Conditionals_post.h
> +  #define X2_INDEP_SGT (AXIS_HAS_STALLGUARD(X2) && defined(X2_STALL_SENSITIVITY))
Don't shorten a name just for the sake of making it shorter. Here a simple copy paste into `X2_SENSORLESS` should suffice just fine.

2019-08-24 18:00 UTC, teemuatlut commented on Marlin/src/lcd/menu/menu_tmc.cpp
> +    #if X2_INDEP_SGT
X2 homing threshold doesn't need to be dependent on the existence of X sensorless capability.

2019-08-24 18:00 UTC, teemuatlut commented on Marlin/src/lcd/menu/menu_tmc.cpp
> +      #if X2_INDEP_SGT
Same here.

2019-08-24 18:00 UTC, teemuatlut commented on Marlin/Configuration_adv.h
> +      #define X2_STALL_SENSITIVITY 8
`#define X2_STALL_SENSITIVITY 8`
I'd suggest changing this to just
`#define X2_STALL_SENSITIVITY X_STALL_SENSITIVITY`
As it will then nicely also handle the default value.

2019-08-24 18:00 UTC, teemuatlut commented on Marlin/src/module/configuration_store.cpp
> +typedef struct {  int16_t X, Y, Z, X2;                                     } tmc_sgt_t;
Don't forget to increase the EEPROM structure version number.

2019-08-24 18:00 UTC, teemuatlut commented on Marlin/src/module/stepper_indirection.cpp
> +        #else
This `else` is unnecessary if you decide to implement my suggestion.

2019-08-25 09:56 UTC, thinkyhead commented
This will get cleaned up and merged later today, following Teemu's suggestions.

2019-08-28 14:05 UTC, AlexandrZloy commented
Sorry, I'm new with github so I don't completely understand how to agreed with your fixes and push them to Marlin repo..

2019-08-28 14:07 UTC, InsanityAutomation commented
@AlexandrZloy Just wait and thinky will get it when he makes it around to it. I dont think theres really anything standing in the way of it at this point but time.

2019-08-28 14:09 UTC, AlexandrZloy commented
@InsanityAutomation ok, I see. Thank you.

2019-08-29 05:11 UTC, thinkyhead commented
This has been rebased, so to get the latest changes use the Git Console and…
```
git fetch origin
git checkout bugfix-2.0.x
git reset --hard origin/bugfix-2.0.x
```

---
For convenience, in the future you should do your work in a copy of `bugfix-2.0.x` and then you can keep your `bugfix-2.0.x` in sync with `upstream` using something like…
```
git checkout bugfix-2.0.x
git fetch upstream
git reset --hard upstream/bugfix-2.0.x
```

2019-08-29 05:15 UTC, merged