Fix G76 reachable test
MarlinFirmware/Marlin pull request #17005
Opened 2020-02-27 10:57 UTC by thinkyhead

Addressing #16995

The `position_is_reachable_by_probe` function accounts for the probe offset, so we just need to pass the position without subtracting the offset.

2020-02-27 18:24 UTC, TheNeskik requested changes
At line 116 'park_pos' should be 'parkpos' without '_'
Same at line 166 and 228.

After the bed is heated to the target temperature, the probe doesn't go down to the heating point.

2020-02-27 20:06 UTC, TheNeskik commented on Marlin/src/gcode/calibrate/G76_M871.cpp
> +    do_blocking_move_to(park_pos);
```suggestion
    do_blocking_move_to(parkpos);
```

2020-02-27 20:06 UTC, TheNeskik commented on Marlin/src/gcode/calibrate/G76_M871.cpp
> +      do_blocking_move_to(park_pos);
```suggestion
      do_blocking_move_to(parkpos);
```

2020-02-27 20:06 UTC, TheNeskik commented on Marlin/src/gcode/calibrate/G76_M871.cpp
> +    bool reachable = position_is_reachable(parkpos) || WITHIN(park_pos.z, Z_MIN_POS - fslop, Z_MAX_POS + fslop);
```suggestion
    bool reachable = position_is_reachable(parkpos) || WITHIN(parkpos.z, Z_MIN_POS - fslop, Z_MAX_POS + fslop);
```

2020-02-28 01:16 UTC, thinkyhead commented
When a test is obviously failing from a typo, and the contributor is off having dinner, there is no need to SPAM the PR about it. We can see compile errors right here on this page already.

2020-02-28 01:16 UTC, thinkyhead commented
@TheNeskik — When a test is obviously failing from a typo, and the contributor is off having dinner, there is no need to SPAM the PR about it. We can see compile errors right here on this page already.

2020-02-28 01:16 UTC, thinkyhead commented
@TheNeskik — When a test is obviously failing from a typo, and the contributor is off having dinner, there is no need to SPAM the PR about it. We can see compile errors right here on this page already.

2020-02-28 01:16 UTC, thinkyhead commented
@TheNeskik — When a test is obviously failing from a typo, and the contributor is off having dinner, there is no need to SPAM the PR about it. We can see compile errors right here on this page already.

2020-02-28 01:16 UTC, thinkyhead commented
@TheNeskik — When a test is obviously failing from a typo, and the contributor is off having dinner, there is no need to SPAM the PR about it. We can see compile errors right here on this page already.

2020-02-28 04:47 UTC, merged