Fix motion over soft. endstop after M84 #20264
MarlinFirmware/Marlin pull request #20283
Opened 2020-11-26 12:21 UTC by Sergey1560

What does this fix:
If HOME_AFTER_DEACTIVATE enabled, but NO_MOTION_BEFORE_HOMING disabled, after M84 (disable steppers) command restriction of software endstop does not work. Limits are calculated for homed axes only. In case of an incorrect start or finish g-code, this may result in damage hardware.

In the command handler G0_G1, movement restrictions are imposed only on the homed axes. M84 drops "homed" flag, and software endstops stop working. 

How it works:
Forces to enable option NO_MOTION_BEFORE_HOMING if option HOME_AFTER_DEACTIVATE is enabled. In this case, after the command M84, the axes cannot move until the command G28. G28 restore "homed" flag and software endstops start working again.

Related Issues #20264

2020-11-26 16:43 UTC, swissnorp commented
I suggest to do the changes in `configuration.h`/`configuration_adv.h` instead of `SanityCheck.h` to add some more transparency.

Somehow like this:

```
#if ENABLED(NO_MOTION_BEFORE_HOMING)  // from Configuration.h.
  //#define HOME_AFTER_DEACTIVATE     // Inhibit movement and require rehoming after steppers are deactivated
#endif
```

2020-11-26 16:46 UTC, swissnorp requested changes

2020-11-26 16:46 UTC, swissnorp commented on Marlin/src/inc/SanityCheck.h
> + * Make sure NO_MOTION_BEFORE_HOMING if NO_MOTION_BEFORE_HOMING enabled
`Make sure NO_MOTION_BEFORE_HOMING if NO_MOTION_BEFORE_HOMING enabled` should be: `HOME_AFTER_DEACTIVATE needs NO_MOTION_BEFORE_HOMING enabled`

2020-11-26 18:36 UTC, Sergey1560 commented
> I suggest to do the changes in `configuration.h`/`configuration_adv.h` instead of `SanityCheck.h` to add some more transparency.

Thank you, your version is really better. I made changes.

2020-11-26 19:05 UTC, swissnorp commented
https://github.com/MarlinFirmware/Marlin/issues/20264#issuecomment-734445473
> Well after thinking a bit more about the issue and the pull request, I must say that this is not a bug and the behaviour is absolutely okey. We may just need to have a note, that HOME_AFTER_DEACTIVATE does not prevent movement!
> 
> NO_MOTION_BEFORE_HOMING: prevents moving if axes not homed, thats the case!
> HOME_AFTER_DEACTIVATE: forces axes to be rehomed after deactivated steppers, thats the case too!
> 
> If you want to prevent movement after steppers have been disabled, you need to enable both of them.

2020-11-26 19:08 UTC, swissnorp requested changes
https://github.com/MarlinFirmware/Marlin/issues/20264#issuecomment-734445473
`//#define HOME_AFTER_DEACTIVATE  // Require rehoming after steppers are deactivated. To also inhibit movement enable NO_MOTION_BEFORE_HOMING from Configuration.h.`

2020-11-27 06:00 UTC, merged

2020-11-27 06:01 UTC, thinkyhead commented
I've opted to apply Anarchism and just document how these work together and put them side by side in the same file.