Fix LCD_BACKLIGHT_TIMEOUT compilation issues
MarlinFirmware/Marlin pull request #24463
Opened 2022-07-07 14:49 UTC by sjasonsmith

### Description

### Requirements

### Benefits

### Configurations

### Related Issues

2022-07-07 14:50 UTC, sjasonsmith commented
My first commit is to verify my new test fails prior to any changes. The actual fix will follow in another push.

2022-07-08 03:18 UTC, thinkyhead requested changes
The `HAS_ENCODER_ACTION` option must be defined before it is used, but it cannot be determined until `Conditionals_adv.h`.

2022-07-08 03:18 UTC, thinkyhead commented on Marlin/src/inc/Conditionals_LCD.h
> +#if ANY(HAS_MARLINUI_MENU, ULTIPANEL_FEEDMULTIPLY, SOFT_RESET_ON_KILL)
The `ULTIPANEL_FEEDMULTIPLY` and `SOFT_RESET_ON_KILL` options aren't available here. They are both defined in `Configuration_adv.h`.

2022-07-08 03:21 UTC, thinkyhead approved these changes

2022-07-08 03:56 UTC, sjasonsmith commented
> The `HAS_ENCODER_ACTION` option must be defined before it is used, but it cannot be determined until `Conditionals_adv.h`.

You are right. I honestly didn't realize that `Conditionals_LCD.h` was included before `Configuration_adv.h` until I went back just now to understand why.

2022-07-08 04:43 UTC, merged

2022-07-08 04:47 UTC, thinkyhead commented
> I went back just now to understand why

Yeah, those three Conditionals files kind of developed organically. There were some conditionals in the first config file that were applied and then used in the second, so we ended up with this intermediary set of conditions, and then it expanded to include anything which can be determined just from the first configuration file. It'll be interesting to see how things rearrange as we get into revamping configuration.