Update Italian language
MarlinFirmware/Marlin pull request #24915
Opened 2022-10-22 08:25 UTC by GMagician

Add missing messages

2022-10-24 14:01 UTC, StuSerious requested changes
Except for the single comment, everything looks fine otherwise!

Grazie!

2022-10-24 14:01 UTC, StuSerious commented on Marlin/src/lcd/language/language_it.h
> +  LSTR MSG_UBL_MESH_INVALID               = _UxGT("Mesh non valido");
Usually when translating, the gender of the world should be relevant to its translation.

In this case, 'mesh' is translated literally to 'rete' or 'maglia', both of which call for female pronouns.

It is therefore more appropriate to use `"Mesh non valida"`

2022-10-24 15:18 UTC, GMagician commented on Marlin/src/lcd/language/language_it.h
> +  LSTR MSG_UBL_MESH_INVALID               = _UxGT("Mesh non valido");
Yep you're right. I think I have to go to school again!

2022-10-24 15:29 UTC, GMagician commented on Marlin/src/lcd/language/language_it.h
> +  LSTR MSG_UBL_MESH_INVALID               = _UxGT("Mesh non valido");
Thanks for your double check

2022-10-25 06:14 UTC, StuSerious commented on Marlin/src/lcd/language/language_it.h
> +  LSTR MSG_UBL_MESH_INVALID               = _UxGT("Mesh non valido");
thanks for the quick fix!

2022-10-29 23:45 UTC, merged