Update toolchain-gccarmnoneeabi for SKR Mini E3 V3/3.0.1 & EBB42
MarlinFirmware/Marlin pull request #26320
Opened 2023-10-02 06:44 UTC by thisiskeithb

### Description

Compiling for an SKR Mini E3 V3, V3.0.1, or BTT EBB42 V1.1, you get the following error:

<details><summary>expand me:</summary>
<p>

```prolog
Compiling .pio/build/STM32G0B1RE_btt/SrcWrapper/src/stm32/pinmap.c.o
/.platformio/packages/framework-arduinoststm32/libraries/SrcWrapper/src/stm32/clock.c: In function 'enableClock':
/.platformio/packages/framework-arduinoststm32/libraries/SrcWrapper/src/stm32/clock.c:135:7: error: a label can only be part of a statement and a declaration is not a statement
  135 |       uint32_t HSEState = RCC_HSE_ON;
      |       ^~~~~~~~
Compiling .pio/build/STM32G0B1RE_btt/SrcWrapper/src/stm32/stm32_def.c.o
Compiling .pio/build/STM32G0B1RE_btt/SrcWrapper/src/stm32/system_stm32yyxx.c.o
Compiling .pio/build/STM32G0B1RE_btt/SrcWrapper/src/stm32/timer.c.o
Compiling .pio/build/STM32G0B1RE_btt/SrcWrapper/src/stm32/uart.c.o
*** [.pio/build/STM32G0B1RE_btt/SrcWrapper/src/stm32/clock.c.o] Error 1
======================================= [FAILED] Took 53.13 seconds =======================================

Environment      Status    Duration
---------------  --------  ------------
STM32G0B1RE_btt  FAILED    00:00:53.128
================================== 1 failed, 0 succeeded in 00:00:53.128 ==================================
```

</p>
</details>

This is due to using `toolchain-gccarmnoneeabi@1.100301.220327`. Updating to `toolchain-gccarmnoneeabi@1.120301.0` fixes the compile error, but does cause a new warning:

```prolog
/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/bin/ld: warning: .pio/build/STM32G0B1RE_btt/firmware.elf has a LOAD segment with RWX permissions
```

That can be silenced with a `-Wl,--no-warn-rwx-segment` build flag ([source](https://community.st.com/t5/stm32-mcus-products/quot-warning-lt-elffile-gt-has-a-load-segment-with-rwx/td-p/83148)), but I'm not sure if that's the best way to handle it.

### Requirements

SKR Mini E3 V3, V3.0.1, or BTT EBB42 V1.1

### Benefits

Allows users to compile for these boards again.

### Configurations

[MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3/BigTreeTech SKR Mini E3 3.0](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3/BigTreeTech%20SKR%20Mini%20E3%203.0)

### Related Issues
- https://github.com/stm32duino/Arduino_Core_STM32/commit/0ffbf3e7f5ad21dcaecfb692c2d4c51531668295#commitcomment-126862592
- https://github.com/stm32duino/Arduino_Core_STM32/issues/2125
- https://github.com/platformio/platform-ststm32/issues/720

2023-10-02 06:55 UTC, thisiskeithb commented
Alternatively, I could have pinned `framework-arduinoststm32` to https://github.com/stm32duino/Arduino_Core_STM32/tree/0c69f378ddf18937fdbdb1f26f61e1308ac7ad51, but this way was easier since I didn't have to modify our `generic_create_variant.py` script to add the commit hash.

2023-10-03 00:11 UTC, classicrocker883 commented
> Alternatively, I could have pinned `framework-arduinoststm32` to https://github.com/stm32duino/Arduino_Core_STM32/tree/0c69f378ddf18937fdbdb1f26f61e1308ac7ad51 (the commit prior to when things broke), but this way was easier since I didn't have to modify our `generic_create_variant.py` script to add the commit hash.

so things "broke" right after this commit made on Sept 1? IIRC, using the previous 12.2re1 tool chain had caused the error that could be silenced with `-Wl,--no-warn-rwx-segment`.

have you found out what exactly made things not work in the first place? or what change made things "fixed" for the most part?

2023-10-03 00:18 UTC, thisiskeithb commented
> edit:
this->[commit here](https://github.com/stm32duino/Arduino_Core_STM32/commit/0ffbf3e7f5ad21dcaecfb692c2d4c51531668295) is the one in question.

I literally linked to that in the PR description.

2023-10-03 03:11 UTC, classicrocker883 commented
> > edit:
> > this->[commit here](https://github.com/stm32duino/Arduino_Core_STM32/commit/0ffbf3e7f5ad21dcaecfb692c2d4c51531668295) is the one in question.
> 
> I literally linked to that in the PR description.

🥇 heres your medal

2023-10-03 03:19 UTC, classicrocker883 commented
```r
".platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/bin/ld.exe:"
```

give no help at all.  
so I was asking if there are any leads as to pinpoint exactly?

i'm painstaking comparing each folder file by file. but ill just not waste my time.

2023-10-03 04:08 UTC, classicrocker883 commented
from [this website]()

> - warning: <file> has a LOAD segment with RWX permissions
>
> This warning indicates that there are one or more vulnerable segments. These segments can be found by running the readelf  program like this:
>
>readelf -lW < file >  
> Note: In readelf’s output, the executable flag for segments is labeled as E rather than X, so look for RWE rather than RWX.  

```r
$ readelf -lW firmware-20231002-235514.elf | grep RWE
  LOAD           0x001000 0x08002000 0x08002000 0x36a80 0x36a80 RWE 0x1000
```
[firmware-20231002-235514.zip](https://github.com/MarlinFirmware/Marlin/files/12788429/firmware-20231002-235514.zip)


honestly I am not exactly sure where to go from here. I'll need to output that address to see what the warning is linked to.  
then I would be able to backtrack to where the package framework file/code is and see what can be done then. otherwise would it just be easier to completely silence the warning with `-Wl,--no-warn-rwx-segment`??

none-the-less I'm interested in finding what the warning pertains to.

2023-10-03 04:45 UTC, classicrocker883 commented
Update
---

I would disregard the whole trying to fix the warning thing. and use `-Wl,--no-warn-rwx-segment` as a build flag.


**--no-warn-rwx-segment** was added to the more recent toolchain, so `toolchain-gccarmnoneeabi@1.100301.220327` doesnt even have the warning available.  
when using `readelf` for the compilation using the previous 10.3.1 toolchain, this is the output
```r
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x08000000 0x08000000 0x39420 0x39420 RWE 0x10000
```
basically the same **RWE** flag is present. that is all what causes the (**RWX**) warning. meaning if program headers give a flag more than **RW**, like we see **RWE** (X being a variable), that's all that it means. It's is informing us that we get **R+W+E**. so thats all.

2023-10-03 04:52 UTC, classicrocker883 requested changes
I would add  
`-Wl,--no-warn-rwx-segment`

2023-10-07 04:28 UTC, thisiskeithb commented
This appears to be a macOS-specific issue with `toolchain-gccarmnoneeabi@1.100301.220327` since CI/compiling under Linux no longer causes the same error: https://github.com/MarlinFirmware/Marlin/pull/26327

2023-10-07 04:57 UTC, thisiskeithb commented
Completely deleting the `~/.platformio/` folder instead of just `/packages/` and `/platforms/` was the fix apparently.

2023-10-07 04:57 UTC, closed without merging