added endstop monitor to M43 command
MarlinFirmware/Marlin pull request #5003
Opened 2016-10-12 00:11 UTC by Bob-the-Kuhn

Added a debug/setup aid that I call endstop monitor.

This routine monitors the endstops and the probe and, if a change is
detected, sends a message to the host and toggles the LED.

This routine runs in the background so normal machine operation is not
affected.

M43 E toggles the function on & off.

The main routine was added to the temperature ISR.  IThe call to the
routine mimics a slow PWM.  It gets called at a 15Hz rate.

It adds 1 global variable and two static variables.

I also updated the pin list in pinsDebug.h.  All the previous pins are
still present.  I took a copy of RCBugFix from 7 Oct, did a grep to get
all the #defines, kept the ones that had a pin, added in all the
previous pins, & then used Excel to create the "#if pin ... print pin
... #endif" sequence.

I'm not sure what the intent of the pin list in pinsDebug.h so just
ignore my changes if they conflict with something.

I also added M43 to the list of implemented commands in Marlin_main.cpp

2016-10-24 07:46 UTC, thinkyhead requested changes

2016-10-24 07:46 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +      SERIAL_PROTOCOLLN((endstop_monitor_flag ? "endstop monitor active" : "endstop monitor disabled"));
Size is more important than performance here.
To optimize string storage / program size, change to:
```cpp
SERIAL_PROTOCOLPGM("endstop monitor ");
SERIAL_PROTOCOL(endstop_monitor_flag ? "en" : "dis");
SERIAL_PROTOCOLLNPGM("abled");
```

2016-10-24 07:46 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +      endstop_monitor_flag = endstop_monitor_flag ? false : true;
```cpp
endstop_monitor_flag ^= true;
```

2016-10-24 07:46 UTC, thinkyhead commented on Marlin/temperature.cpp
> +        SERIAL_PROTOCOLPGM("\n");
`SERIAL_PROTOCOLPGM("\n\n")` is fine here.

2016-10-24 07:46 UTC, thinkyhead commented on Marlin/temperature.cpp
> +   */
Comments like this should be placed above the function definition rather than within it.

2016-10-24 07:46 UTC, thinkyhead commented on Marlin/pinsDebug.h
> +  #if defined(X_STOP_PIN) && X_STOP_PIN > -1
When a pin name actually ends with `_PIN` you should use the `PIN_EXISTS` macro. In this case `PIN_EXISTS(X_STOP)`. For the "`STOP`" pins, also check whether they are equal to the `MIN` or `MAX` pins, and don't bother displaying them if they're assigned so.

2016-10-24 07:46 UTC, thinkyhead commented on Marlin/pinsDebug.h
> +    PIN_SAY(__FD)
All the `PIN_SAY` lines should end with a semicolon. To get rid of compiler complaints, remove the semicolon I accidentally left at the end of the `PIN_SAY` macro definition.

2016-10-24 17:28 UTC, Bob-the-Kuhn commented on Marlin/pinsDebug.h
> +  #if defined(X_STOP_PIN) && X_STOP_PIN > -1
I disagree about the "STOP" pins.  Reporting that they exist shouldn't be a problem.  Keeping people from writing to them is a must.

The "don't report protected pins" function is already implementd in the M43 command.  It checks if the pin is protected before calling the "report_pin_name" function so the M43 command won't print out anything about the endstops.

2016-10-24 17:54 UTC, Bob-the-Kuhn commented on Marlin/pinsDebug.h
> +  #if defined(X_STOP_PIN) && X_STOP_PIN > -1
I disagree about the "STOP" pins.  Reporting that they exist shouldn't be a problem.  Keeping people from writing to them is a must.

The "don't report protected pins" function is already implemented in the M43 command.  It checks if the pin is protected before calling the "report_pin_name" function so the M43 command won't print out anything about the endstops.

2016-10-24 17:55 UTC, Bob-the-Kuhn commented on Marlin/pinsDebug.h
> +    PIN_SAY(__FD)
Did the same thing for ANALOG_PIN_SAY

2016-10-24 18:00 UTC, Bob-the-Kuhn commented
Implemented everything requested by Scott except for the "don't report protected pins" function.

In addition a)  I removed the ";" from the ANALOG_PIN_SAY macro definition so the  ANALOG_PIN_SAY lines would end in a semicolon and b) in temperature.cpp moved the static defines into the routine so that all the endstop monitor items are in one place.

I don't see any problems with reporting that a protected pin exists.  Keeping someone from writing to them is a must.

The "don't report protected pins" function is already implemented in the M43 command.  It checks if the pin is protected before calling the "report_pin_name" function so the M43 command won't print out anything about the endstops.

2016-10-26 11:28 UTC, thinkyhead commented
> except for the "don't report protected pins" function

I didn't request this. I did request that you display the endstop pins only once instead of duplicating them with two different names, however. Perhaps that what came across incorrectly.

2016-10-26 14:22 UTC, Bob-the-Kuhn commented
Now I understand ...

There are 24 boards that use STOP instead of MAX/MIN. Pins.h assigns them to either MAX or MIN depending on the home direction.

I think it would be confusing for the owners of these boards to see a different name listed than what's in the pins_xxx file.

I can easily delete the STOP pins from the list if that's what you still want.

2016-10-27 06:37 UTC, Bob-the-Kuhn commented
We can stop scanning pins 70 and above.  The tables in pins_arduino.h for the mega only go from 0-69 so digitalRead just reports "0" for all pins above 69.

2016-10-28 14:02 UTC, Bob-the-Kuhn commented
I've commented out the STOP pins.

Doesn't really matter because the corresponding MAX/MIN pin is encountered first at which point the search stops.

2016-10-28 22:05 UTC, Bob-the-Kuhn commented
**M43 - made report pretty & added PWM info** 

**pinsDebug** changes
    made things line up in columns
    added extended report
        PWM info added in the extended report

**Marlin_main.cpp** changes
    changed one line in M43 routine
        if no options selected now does extended report
            added "hidden" option to make the extended report ignore the protected status
   brought Marlin_main.cpp up to date with 26 OCT RCBugFix

2016-10-28 23:58 UTC, Bob-the-Kuhn commented
missed some updates to Marlin_main.cpp 

Today's earlier update was done against an out of date copy of RCBugFix.

This one was done against 28 OCT 5:15 PM Central time zone.

2016-10-29 00:49 UTC, Bob-the-Kuhn commented
Found a bug in the pinsDebug.h file.

I'll sit on it until this PR bubbles up on Scott's to-do-list for him to look at it.

2016-10-29 19:30 UTC, Bob-the-Kuhn commented
This PR has been replaced (cloned) by PR #5112

2016-10-29 19:30 UTC, closed without merging