Replace const bool with #define for consistency
MarlinFirmware/Marlin pull request #5191
Opened 2016-11-09 16:56 UTC by petrzjunior

In `Configuration.h` there is an option `const bool FIL_RUNOUT_INVERTING = false;` declared as `const bool` for no clear reason. I replaced it with `#define` to keep consistency (automated enable/disable scripts will profit). Also changed a line in `Marlin_main.cpp` to keep compatibility. Hex size didn't increase.

2016-11-12 19:09 UTC, thinkyhead requested changes
Looks good. Just one thing…

2016-11-12 19:09 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +    if ((IS_SD_PRINTING || print_job_timer.isRunning()) && !(READ(FIL_RUNOUT_PIN) != FIL_RUNOUT_INVERTING))
Might as well do:
```cpp
if ((IS_SD_PRINTING || print_job_timer.isRunning()) && READ(FIL_RUNOUT_PIN) == FIL_RUNOUT_INVERTING)
```

2016-11-12 19:09 UTC, thinkyhead commented on Marlin/Configuration.h
> +  #define FIL_RUNOUT_INVERTING false // set to true to invert the logic of the sensor.
Can you do the same in all the `Configuration.h` files in `example_configuration` too? Thanks!

2016-11-13 09:28 UTC, petrzjunior commented on Marlin/Configuration.h
> +  #define FIL_RUNOUT_INVERTING false // set to true to invert the logic of the sensor.
Oh, totally forgot about example ones :)

2016-11-13 11:05 UTC, petrzjunior commented
Done.

2016-11-16 05:54 UTC, thinkyhead requested changes

2016-11-16 05:54 UTC, thinkyhead commented on Marlin/example_configurations/Felix/Configuration.h
> +  #define FIL_RUNOUT_INVERTING = false; // set to true to invert the logic of the sensor.
```cpp
#define BLAH_DE_BLAH = false;
```
That would result in substitution of `BLAH_DE_BLAH` with `= false;`. Probably not what we want.

2016-11-16 17:57 UTC, petrzjunior commented on Marlin/example_configurations/Felix/Configuration.h
> +  #define FIL_RUNOUT_INVERTING = false; // set to true to invert the logic of the sensor.
Oh, I deserve a big facepalm. Probably made more mess than benefit. Should be OK now.

2016-11-17 09:37 UTC, thinkyhead approved these changes

2016-11-17 09:37 UTC, merged