Update to Danish language 10/11-2016
MarlinFirmware/Marlin pull request #5200
Opened 2016-11-10 19:55 UTC by boelle

2016-11-11 07:50 UTC, Kaibob2 reviewed
@boelle Aren't there a few lines which are too long to be displayed properly on common LCD displays? Only asking.

2016-11-12 19:00 UTC, thinkyhead requested changes
@boelle Please make the requested changes.

2016-11-12 19:00 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_INFO_PRINT_FILAMENT           "Extruderet"
These defines are screwed up, and there are two of each. They belong inside the conditionals as you see above. Please put them back as they were.

2016-11-12 19:00 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_LEVEL_BED_WAITING               "Tryk for at starte bed level"
These strings are for use on LCD controllers, which have a nominal limit of 20 characters. Translators are asked to strive for 18 or fewer characters, if possible, and 16 or fewer characters ideally.

2016-11-12 19:00 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_HOME_OFFSETS_APPLIED            "Forskydninger af home pos. er tilføjet"
These strings are for use on LCD controllers, which have a nominal limit of 20 characters. Translators are asked to strive for 18 or fewer characters, if possible, and 16 or fewer characters ideally.

2016-11-12 19:00 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_E                               "E"
You should remove `MSG_X`, `MSG_Y`, `MSG_Z`, and `MSG_E` (which were intentionally removed).

2016-11-12 19:00 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_HEATING_FAILED_LCD              "Opvarmning mislykkedes"
These strings are for use on LCD controllers, which have a nominal limit of 20 characters. Translators are asked to strive for 18 or fewer characters, if possible, and 16 or fewer characters ideally.

2016-11-12 19:00 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_ERR_MAXTEMP                     "Fejl: Maks temp"
This is fine, but I thought we agreed that `MAKSTEMP` and `MINTEMP` were more isomorphic translations.

2016-11-12 19:00 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_PLEASE_RESET                    "Reset Venligst"
Check your line-endings and make sure they are "Unix" style (just LF with no CR).

2016-11-12 19:00 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_FILAMENT_CHANGE_RESUME_1        "Fortsætter..."
As in the block above, these belong inside the conditionals. Please restore them as they were.

2016-11-12 19:52 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_LEVEL_BED_WAITING               "Tryk for at starte bed level"
done

2016-11-12 19:53 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_HOME_OFFSETS_APPLIED            "Forskydninger af home pos. er tilføjet"
done

2016-11-12 19:53 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_E                               "E"
done

2016-11-12 19:54 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_HEATING_FAILED_LCD              "Opvarmning mislykkedes"
done

2016-11-12 19:54 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_ERR_MAXTEMP                     "Fejl: Maks temp"
i missed that.

2016-11-12 19:55 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_PLEASE_RESET                    "Reset Venligst"
Blame github. i edit via web exclusive

2016-11-12 19:56 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_INFO_PRINT_FILAMENT           "Extruderet"
oki, i just cut out from the english will add the conditionals

2016-11-12 19:56 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_FILAMENT_CHANGE_RESUME_1        "Fortsætter..."
will do as above

2016-11-12 20:03 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_INFO_PRINT_FILAMENT           "Extruderet"
so like this: 
#ifndef MSG_INFO_MENU
#define MSG_INFO_MENU                       "Om Printer"
#endif

2016-11-12 20:04 UTC, boelle commented
about the conditionals... like this:

#ifndef MSG_INFO_MENU
#define MSG_INFO_MENU                       "Om Printer"
#endif

line 183-185

2016-11-12 20:28 UTC, boelle commented
@thinkyhead think i got it, might have failed totally

2016-11-15 20:32 UTC, boelle commented
@thinkyhead did i get it right on the conditionals ? or are there still faults?

2016-11-16 05:38 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_INFO_PRINT_FILAMENT           "Extruderet"
I see you figured out I was referring to
```cpp
#if LCD_WIDTH > 19
  . . .
#else
  . . .
#endif
```
But you neglected to restore the proper indentation.

2016-11-16 05:39 UTC, thinkyhead commented on Marlin/language_da.h
> +#define MSG_FILAMENT_CHANGE_RESUME_1        "Fortsætter..."
And again, formatting counts if you want a passing grade.

2016-11-16 05:41 UTC, thinkyhead commented
See my additional comments.

2016-11-16 09:43 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_INFO_PRINT_FILAMENT           "Extruderet"
i assume you mean i missed 1 space ident

2016-11-16 09:43 UTC, boelle commented on Marlin/language_da.h
> +#define MSG_FILAMENT_CHANGE_RESUME_1        "Fortsætter..."
i assume you mean i missed 1 space ident

2016-11-16 09:43 UTC, boelle commented
@thinkyhead one space ident added to the 2 conditionals sections

2016-11-17 09:46 UTC, thinkyhead requested changes
Please fix the issues I have pointed out. Thanks!

2016-11-17 09:46 UTC, thinkyhead commented on Marlin/language_da.h
> + #define MSG_INFO_PRINT_FILAMENT           "Total Extruderet"
Please indent with 2 spaces. Thanks!

2016-11-17 09:46 UTC, thinkyhead commented on Marlin/language_da.h
>  #else // LCD_HEIGHT < 4
Somehow this has both `#endif` and `#else`. Please fix.

2016-11-17 09:46 UTC, thinkyhead commented on Marlin/language_da.h
>  #else
Only `#else` is needed. Somehow an extra `#endif` crept in.

2016-11-17 09:46 UTC, thinkyhead commented on Marlin/language_da.h
> + #define MSG_INFO_PRINT_FILAMENT           "Total Extruderet"
This first group seems to be missing these:
```
MSG_INFO_MIN_TEMP
MSG_INFO_MAX_TEMP
MSG_INFO_PSU
MSG_DRIVE_STRENGTH
MSG_DAC_PERCENT
MSG_DAC_EEPROM_WRITE
MSG_FILAMENT_CHANGE_HEADER
MSG_FILAMENT_CHANGE_OPTION_HEADER
MSG_FILAMENT_CHANGE_OPTION_EXTRUDE
MSG_FILAMENT_CHANGE_OPTION_RESUME
```
Note that for items where the string length doesn't differ, they don't need to be inside the conditional and can be declared just once.

2016-11-17 22:42 UTC, boelle commented on Marlin/language_da.h
> + #define MSG_INFO_PRINT_FILAMENT           "Total Extruderet"
Done

2016-11-17 22:45 UTC, boelle commented on Marlin/language_da.h
> + #define MSG_INFO_PRINT_FILAMENT           "Total Extruderet"
I could not find them in the english file which i have copied off

But will add them if i dont hear anything else

2016-11-17 22:46 UTC, boelle commented on Marlin/language_da.h
>  #else
#endif removed

2016-11-17 22:46 UTC, boelle commented on Marlin/language_da.h
>  #else // LCD_HEIGHT < 4
#endif removed

2016-11-17 23:34 UTC, boelle commented
@thinkyhead did i pass this time? or is this section in fact missing thou i fail to see it in the english file

MSG_INFO_MIN_TEMP
MSG_INFO_MAX_TEMP
MSG_INFO_PSU
MSG_DRIVE_STRENGTH
MSG_DAC_PERCENT
MSG_DAC_EEPROM_WRITE
MSG_FILAMENT_CHANGE_HEADER
MSG_FILAMENT_CHANGE_OPTION_HEADER
MSG_FILAMENT_CHANGE_OPTION_EXTRUDE
MSG_FILAMENT_CHANGE_OPTION_RESUME

2016-11-18 03:59 UTC, thinkyhead commented
> i fail to see it in the english file

https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/language_en.h#L526

2016-11-18 04:11 UTC, thinkyhead commented
Rebased, squashed, and patched at #5244

2016-11-18 04:11 UTC, closed without merging