Show more decimals in Display, if possible
MarlinFirmware/Marlin pull request #5337
Opened 2016-12-01 14:41 UTC by Guthenberg

_123, -123, _-12, or __-1 format=>
1234, -123, 12.3, _123, _-12, or __-1 format

2016-12-01 14:45 UTC, Guthenberg commented
I would like to see the position more accuratly and show decimals if possible.
I am kindof new to this, but I think it would help some people.

2016-12-01 19:53 UTC, thinkyhead commented
Still working on it? It's a good idea if we have some places where values passed to `itostr4sign` might go over +999, but not lower than -999.

2016-12-01 20:34 UTC, Guthenberg commented
I had a bug in there. I hope I'll find some time to post a improved version tomorrow.

2016-12-02 11:58 UTC, boelle commented
if space on display is a problem maybe consider to drop things that are not so relavant... ie during print drop X and Y cords, they dont make sense anyway

2016-12-02 13:16 UTC, Guthenberg commented
Found my mistake: DIGIMOD changed.
@ boelle: but this change is meant to make the x and y - Axis-Position more precise - if possible - without of using any extra space on the display: I often print parts that are less than 100mm in size. Therefore a more precise position would be helpfull ( for example 98.7mm). But If I am Printing very large parts it is usefull tu be able to see up to 9999mm. At the same time I want to see positions in the negative Range (like -1.2 or -999).

2016-12-02 14:05 UTC, boelle commented
hehe

what i mean is that the cords change so fast during printing that it at least to me make less sense to have them

during setup etc yes then it makes sense

2016-12-03 07:39 UTC, thinkyhead commented
@Guthenberg Can you squash the commits down to 1? Use the following:

```
git rebase -i HEAD~6
git push -f
```

2016-12-03 07:40 UTC, thinkyhead requested changes
See https://github.com/MarlinFirmware/Marlin/wiki/DNE-Coding-Standards

2016-12-03 07:40 UTC, thinkyhead commented on Marlin/utility.cpp
> +if (!cond1||(cond0&&!cond2)) {
Spacing counts. Please adhere to the style established by the rest of the code.

2016-12-05 07:42 UTC, Guthenberg commented
You're right formatting matters Must have happened when I copyed my changes to the online editor. I hope my last commit fixes the formatting issues. 
Since I've been editing online I have to figure out how to do the squashing.

2016-12-05 13:41 UTC, Guthenberg commented
OK, figured that out, I hope.

2016-12-05 15:03 UTC, thinkyhead commented
Superseded by #5385 — Implemented as an optional feature.

2016-12-05 15:03 UTC, closed without merging