Nozzle Wipe Vertical Zig-Zag
MarlinFirmware/Marlin pull request #5444
Opened 2016-12-09 06:22 UTC by hexane360

- Adds configuration support for zig-zags in either the X or Y axis, for
wipe pads significantly longer in one dimension
- Adds configuration for default number of zig-zag triangles, vs. a
magic number in Marlin_main.cpp
- Updates description of auto nozzle wiping to match functionality

(also I'm not sure Version.h and Configuration.h are incremented
correctly)

2016-12-09 11:11 UTC, thinkyhead requested changes
A few changes needed.
- Search-and-replace "VERSION 010101" with "VERSION 010100"
- Automate `NOZZLE_CLEAN_HORIZONTAL` (one fewer user option)

2016-12-09 11:11 UTC, thinkyhead commented on Marlin/Configuration.h
> +#define CONFIGURATION_H_VERSION 010101
We can leave this at 010100. It will change to 010101 when we publish version 1.1.1.

2016-12-09 11:11 UTC, thinkyhead commented on Marlin/Configuration.h
> +  #define NOZZLE_CLEAN_HORIZONTAL
We might not need this as a user option. (Fewer options good!)

If the cleaning area is longer along the X direction then we know the zig-zags are vertical. If the cleaning area is longer along the Y direction then we know the zig-zags are horizontal.

Instead, we can put the following into `nozzle.h` to make arrays that the pre-compiler can see (i.e., no code):
```cpp
constexpr float nozzle_clean_start_point[4] = NOZZLE_CLEAN_START_POINT,
                nozzle_clean_end_point[4] = NOZZLE_CLEAN_END_POINT;
constexpr bool NOZZLE_CLEAN_HORIZONTAL = fabs(nozzle_start_point[X_AXIS] - nozzle_end_point[X_AXIS]) < fabs(nozzle_start_point[Y_AXIS] - nozzle_end_point[Y_AXIS]);
```

2016-12-09 11:18 UTC, thinkyhead commented on Marlin/nozzle.h
> +        #if ENABLED(NOZZLE_CLEAN_HORIZONTAL)
If we use `constexpr bool NOZZLE_CLEAN_HORIZONTAL`, these lines change to regular
`if (NOZZLE_CLEAN_HORIZONTAL) { . . . }` blocks…. Or better yet, use ternary expressions:
```cpp
const float A = fabs( NOZZLE_CLEAN_HORIZONTAL ? end.y - start.y : end.x - start.x), // [twice the] Amplitude
            P = fabs(!NOZZLE_CLEAN_HORIZONTAL ? end.y - start.y : end.x - start.x); // Period
```
Use the same for `const float x` and `const float y` below.

2016-12-09 11:22 UTC, thinkyhead commented on Marlin/nozzle.h
> +            #endif // NOZZLE_CLEAN_HORIZONTAL
e.g.,
```cpp
const float x = start.x + ( NOZZLE_CLEAN_HORIZONTAL ? i * P : (A/P) * (P - fabs(fmod((i*P), (2*P)) - P))),
            y = start.y + (!NOZZLE_CLEAN_HORIZONTAL ? i * P : (A/P) * (P - fabs(fmod((i*P), (2*P)) - P)));
```

2016-12-10 15:58 UTC, hexane360 commented
I have made the changes you suggested. If there's anything else needed to standardized or improve the code, let me know.

2017-01-12 15:19 UTC, merged

2017-01-12 15:47 UTC, thinkyhead commented
Oops. @hexane360 Can you re-do this, but for `RCBugFix` instead of `RC`?

2017-01-12 18:28 UTC, hexane360 commented
Yeah. I submitted a PR [here](https://github.com/MarlinFirmware/Marlin/pull/5686).