piston extruder 5339
MarlinFirmware/Marlin pull request #5469
Opened 2016-12-11 20:14 UTC by BillStruve

##Why (short version)
Printing by extruding a paste with a stepper motor driven piston does not require
temperature control of the extruder head or the bed.

It does require control of a fan to dry the paste after extrusion.
When not dried, the print will collapse when it is tall.
The manufacturer provides a warm air blower fan for this.
	M35 turns fan on, M36 turns fan off.
	
It also requires a means of adjusting the extrude rate during printing.
The manufacturer has provided a pot with a knob for the user.
	M37 A# - turns on/off the E multiplier Adjustment
	M37 S# - turns on/off Showing of the E multiplier
	M37 R##.# - adjusts the sensitivity of the knob (%)
		equation: y = mx + b  where y = multiplier,
		m = R/100/512,  x = ADC reading, b is calculated
		assuming (max x)/2 = 512 and at the midpoint of the
		adjustment, the multiplier will be 1.000
	
##What (overview)
Configuration.h
	add a section for a piston extruder printer
	add 2 defines to direct compiler
	add 2 default values
Marlin.h
	add 6 extern vars for use in Marlin_main.cpp,
		planner.cpp, and temperature.cpp
Marlin_main.cpp
	set initial values for vars
	add descriptions for M35, M36, and M37
	add code for M35, M36, and M37
	add case's for M35, M36, and M37
enum.h
	add a Prepare/Measure pair for ADC
pins_RAMPS.h
	define a pin for the dryer fan
	define a pin for the ADC input
planner.cpp
	alter extrusion with E multiplier
temperature.cpp
	setup for analog read
	use analog read to calculate E multiplier
	provide user feedback of E multiplier
example_configurations
	add MMM folder
	add a specific Configuration.h to MMM folder

2016-12-13 11:24 UTC, thinkyhead commented on Marlin/Configuration.h
> +#ifdef PISTON_EXTRUDER
Please use `#if ENABLED(...)` for options like these.

2016-12-13 11:25 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +#ifdef PISTON_EXTRUDER
#if ENABLED(PISTON_EXTRUDER)

2016-12-13 11:26 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +    WRITE(DRYER_FAN_PIN, 1);
Please use `HIGH` instead of `1`.

2016-12-13 11:26 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +    WRITE(DRYER_FAN_PIN, 0);
Please use `LOW` rather than `0`.

2016-12-13 11:27 UTC, thinkyhead commented on Marlin/pins_RAMPS.h
> +#ifdef PISTON_EXTRUDER
`#if ENABLED(PISTON_EXTRUDER)`

2016-12-13 11:28 UTC, thinkyhead commented on Marlin/pins_RAMPS.h
> +  #ifdef E_ADJUST_MANUALLY
`#if ENABLED(E_ADJUST_MANUALLY)`

2016-12-13 11:31 UTC, thinkyhead commented on Marlin/pins_RAMPS.h
> +#endif
And... Actually, when defining pins for a specific function in the pins files, don't set conditions on them. We're defining the default pins that _will be used_ when the feature that uses them is enabled. When the feature is disabled, we just don't touch the pins.

2016-12-13 11:33 UTC, thinkyhead commented on Marlin/planner.cpp
> +  #endif
Marlin code is leaning towards this style, to reduce repetition:
```cpp
float esteps_float = de * volumetric_multiplier[extruder] * flow_percentage[extruder] * 0.01
  #if ENABLED(E_ADJUST_MANUALLY)
    * e_adjust_multiplier
  #endif
;
```

2016-12-13 11:37 UTC, thinkyhead commented on Marlin/temperature.cpp
> -      break;
Here I suggest keeping `MeasureTemp3` mostly as it was, but just override the new state it sets:
```cpp
temp_state =
  #if ENABLED(E_ADJUST_MANUALLY)
    Prepare_e_adjust_reading
  #else
    Prepare_FILWIDTH
  #endif
;
```

2016-12-13 11:39 UTC, thinkyhead commented on Marlin/temperature.cpp
> +      case Prepare_e_adjust_reading:
…and then you can have `#if ENABLED(E_ADJUST_MANUALLY)` just above this line ^

2016-12-13 11:40 UTC, thinkyhead requested changes
Looking pretty good. Patch up with the requested changes, rebase, squash, and `git push -f` the updated branch.

2016-12-13 14:17 UTC, BillStruve commented
Made all changes. Do the 'rebase' and 'squash' get done before the add and commit to my fork?

2016-12-15 17:25 UTC, BillStruve commented
Does anything else need to be done?

2016-12-19 17:18 UTC, closed without merging

2016-12-19 17:19 UTC, BillStruve commented
Updated to make E adjust independent of dryer fan.