guaranteed BLTouch detection
MarlinFirmware/Marlin pull request #5729
Opened 2017-01-22 00:13 UTC by Bob-the-Kuhn

To guarantee that the 5mS pulse from a BLTouch is recognized you need to have the endstops.update() routine run twice in that 5mS period.

At 200 steps per mm, my system has problems  below a feedrate of 120 mm per minute.

Two things were done to guarantee the two updates within 5mS:
1) In interrupt mode, a check was added to the temperature ISR.  If the endstop interrupt flag/counter is active then it'll kick off the endstop update routine every 1mS until the flag/counter is zero.  This flag/counter is decremented by the temperature ISR AND by the stepper ISR.

2) In poling mode, code was added to the stepper ISR that will make sure the ISR runs about every 1.5mS.  The "extra" ISR runs only check the endstops.  This was done by grabbing the intended ISR delay and, if it's over 2.0mS, splitting the intended delay into multiple smaller delays.  The first delay can be up to 2.0mS, the next ones 1.5mS (as needed) and the last no less than 0.5mS.

2017-01-22 01:58 UTC, Grogyan commented
I was going to ask about this,  as I might just be able to upgrade my old RC6BugFix to RC8BugFix. 
Main problem has been detecting, reliably the BLTouch on G28

2017-01-22 02:41 UTC, Roxy-3D commented
I'm going to look at this much more closely very soon.   But this looks like exactly what we need.

Also, I'm going to as the BL-Touch people to review it.   It would be nice to put all these BL-Touch problems behind us and have it work flawlessly!

2017-01-22 02:48 UTC, Bob-the-Kuhn commented
RC8 has some BLTouch bug fixes in it.  You definitely want to be running RC8.

The other thing is right now RCBugFix has a minimum feedrate requirement for reliable detection of the 5mS pulse from a BLTouch.  This PR eliminates that issue.

The minimum feedrate calculation is 24000 divided by steps per unit.  On my system I have 198 steps per mm so my minimum feedrate is 121mm/minute.  I can attest that on my system a feedrate of 120mm/minute results in seemingly random head crashes.

My config_adv file has a HOMING_BUMP_DIVISOR of 4 for the Z axis so my minimum homing feedrate on the Z axis is 4 x 121 mm/minute = 484 mm/minute.

#define HOMING_BUMP_DIVISOR {2, 2, 4}  // Re-Bump Speed Divisor (Divides the Homing Feedrate)

2017-01-22 03:26 UTC, Bob-the-Kuhn commented
Here are some screen captures that show how the polling and interrupt modes work.  I put some writes to I/O pins in the code so I could tell when the endstop update routine was run, when the Stepper ISR was run and when the endstop update routine declared a valid endstop detection.

Hmmm - on the last one it looks like the probe fell off the pin so it doesn't directly show when the stepper ISR is run.  In the interrupt mode the stepper ISR is only run when a step pulse is needed.
 
![z split example](https://cloud.githubusercontent.com/assets/20692583/22179632/4757e7aa-e01f-11e6-9fe6-42d44c560838.jpg)

========================================================

![bltouch polling](https://cloud.githubusercontent.com/assets/20692583/22179631/47545ff4-e01f-11e6-92de-1cafe98509fe.jpg)

=======================================================

![bltouch interrupt](https://cloud.githubusercontent.com/assets/20692583/22179630/47523620-e01f-11e6-9642-81ba6596ae33.jpg)

2017-01-22 03:30 UTC, Bob-the-Kuhn commented
@Roxy-3D  - my first idea was to put the BLTouch into the M119 mode whenever it deployed.  That would have been only 2-3 lines of code.

As best I can tell there has to be a delay between the deploy servo command and the M119 servo command.  I couldn't get it to reliably go into the M119 mode even with delays long enough to trip the WDT.

You might want to ask the BLTouch folks how to reliably enter into the M119 mode.

2017-01-22 03:35 UTC, Roxy-3D commented
@Bob-the-Kuhn     Bob, I have a couple of questions:

- Did you experiment with the Configuration.h #define ENDSTOP_INTERRUPTS_FEATURE  Did it work with your BL-Touch probe?
- Assuming that functionality can be used with BL-Touch probes to resolve the issue, how hard would it be to add stuff to your code to make an intelligent choice of how to resolve the problem?  What I'm kind of thinking (and please correct me if I'm wrong!!!) in general it would be best to just have the BL-Touch generate an interrupt and use that to lock in the point.  But if that can't be done (for example, the BL-Touch is not on a pin that can generate an interrupt) we enable these pieces of code to resolve the issue.

2017-01-22 03:38 UTC, Roxy-3D commented
> You might want to ask the BLTouch folks how to reliably enter into the M119 mode.

Do you mean the new mode that reports the probe's activation (or not) without a pulse?   If so, that is a new feature that is being added and I have not seen a BL-Touch with that capability yet.   But I believe that mode is activated by setting the servo angle to 60 degrees.

2017-01-22 04:10 UTC, Bob-the-Kuhn commented
@Roxy-3D - interrupt mode or polling mode is selected by enabling/disabling the ENDSTOP_INTERRUPTS_FEATURE in configuration.h.

When the ENDSTOP_INTERRUPTS_FEATURE is enabled a BLTouch (or any other endstop) causes the endstop ISR to run.  That sets a flag/counter to 2.  This kicks the stepper ISR into polling the endstops.  My change was to also have the temperature ISR poll the endstops when the flag/counter is active (not zero).   The end result is the endstops get polled at least every millisecond after the endstop ISR runs.

2017-01-22 04:11 UTC, Roxy-3D commented
OH!!!!!   I get it!    (I haven't looked at the code changes carefully yet!)

2017-01-22 04:37 UTC, Bob-the-Kuhn commented
@Roxy-3D - M119 mode

Using the M280 P0 Sxxx manual instructions I found out the M119 mode command  (servo angle 60) must be issued after the deploy command (servo angle 10).  The M119 command is ignored if issued before the deploy command.

I first added a line to the code that issues a M119 mode command (servo angle 60) right after the deploy command (servo angle 10).  That only gave me 5mS pulses.  

I then added a delay between the two lines in the code.  I didn't see the BLTouch output change from "5mS pulse high" to "high level until stow" until the delay was in the 750mS range.  The problem was that I didn't find a delay that always resulted in the "high level until stow" functionality even when I got to the point where the WDT reset the board.  

If there is a way to reliably enter the M119 mode then the code changes would amount to just adding 4 lines of code right after the deploy command:
```
servo[Z_ENDSTOP_SERVO_NR].move(deploy ? BLTOUCH_DEPLOY : BLTOUCH_STOW);
if (deploy) {
  delay(???);
  servo[Z_ENDSTOP_SERVO_NR].move(BLTOUCH_M119_MODE);
}
```

2017-01-27 02:55 UTC, Roxy-3D commented
@Bob-the-Kuhn  I have a message out to Antclabs (the maker of BL-Touch).   It takes a little bit of time to get the very technical English translated into something they can use and then a little more time to get a response.     

I think I would prefer if a servo angle of 60 degrees put things into 'switch mode' but there may be a reson for why things are as you report.    I'll keep you posted on what ever I hear.

2017-01-27 03:12 UTC, Bob-the-Kuhn commented
Understood.  I've dealt with Asian companies on technical topics as part of my former job.  It can be "interesting".

2017-02-08 05:55 UTC, Bob-the-Kuhn commented
Added some code to try to recover the BLTouch from it's error state if the BLTouch is active immediately after being deployed.

Code provided by @Roxy-3D 

I tried it without issues a couple of dozen times.  In each case the error state was released and the probing went on as usual.

2017-02-08 06:38 UTC, Roxy-3D commented
> I tried it without issues a couple of dozen times.  In each case the error state was released and the probing went on as usual.

I haven't done it yet...  But I was thinking it made sense to also do the BL-Touch reset (if needed) and init() time.   It doesn't really matter because it happens when G28 deploys the probe to home, but it would be nice to get the blinking red error light off right away....

2017-02-08 15:26 UTC, Bob-the-Kuhn commented
Yes, at init time would be a nice addition.

The only way I see a peaceful future using the new/improved S60 mode is if we make it a configuration option.  Otherwise owners of the older ones will be having problems.

I don't think that the new/improved S60 mode has any value for us.

2017-02-08 21:44 UTC, Bob-the-Kuhn commented
@Roxy-3D - I've added BLTouch init code to the startup section.

2017-02-08 23:18 UTC, Roxy-3D commented
> I've added BLTouch init code to the startup section.

One thought I had after I typed that in...   At init() time, the BL-Touch reset won't be successful if the nozzle is too close to the bed.   The pin will attempt to deploy, but it will hit the bed and the error state will come right back.   But even in that degenerate case...   The Z-Probe will raise enough when trying to deploy the probe for the G28 and the deploy code will notice the BL-Touch is in an error state.  It will still get cleared at that point in time.   But the user will have to see a blinking red light for the first part (X & Y) of the homing operation.

2017-02-10 21:48 UTC, thinkyhead requested changes
Overall it looks very good. Some small changes are needed, but otherwise it seems ready to merge.

2017-02-10 21:48 UTC, thinkyhead commented on Marlin/stepper.cpp
> +  #define OCR_VAL_TOLERANCE 1000          // first delay max is 2.0mS, last delay min is 0.5mS, all others 1.5mS
This line is doubled.

2017-02-10 21:48 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +    give_bltouch_a_command( BLTOUCH_STOW );         // error condition.
No extra spaces within parentheses.

2017-02-10 21:48 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +        give_bltouch_a_command( BLTOUCH_STOW );         // condition.
No extra spaces within parentheses.

2017-02-10 21:48 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +      for( i=0; i<15; i++) {                  // wait a short time.
This is preferred:
```cpp
for (uint8_t i = 0; i < 15; ++i) {
```

2017-02-10 21:57 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +      for( i=0; i<15; i++) {                  // wait a short time.
Actually, this is even better: `safe_delay(375);`

2017-02-10 22:13 UTC, thinkyhead commented
PR submitted to https://github.com/Bob-the-Kuhn/RCBugfix-M43-and-spindle/pull/1

2017-02-10 22:28 UTC, Bob-the-Kuhn commented
All requested changes have been implemented.

2017-02-11 00:56 UTC, thinkyhead commented
Some tweaks at https://github.com/Bob-the-Kuhn/RCBugfix-M43-and-spindle/issues/2

2017-02-11 18:22 UTC, Bob-the-Kuhn commented
Scott's changes have been merged, I've tested the code & the commits have been squashed into one.

I think it's ready for prime time.

2017-02-12 04:01 UTC, DynamiteHack commented
Hello guys. I have followed the "**BLTouch not deploying**" trail to, I believe, its end here. I am not sure if this is the appropriate place for this comment so, feel free to redirect me!!

I started yesterday to update the firmware on my FolgerTech 2020 i3. I have been using the firmware FT supplied. I had installed a BLTouch a month or so ago. Mechanically, everything seemed to work okay. I was having some problems with my prints starting too high (Z Offset not accounted for). 

While researching that issue and seeing all of the work you guys have been doing with the BLTouch, I figured I'd give updating my firmware a try! 

I compared my original Configuration.h line by line with the latest from RC8 (completely new layout!!). I also went through the Configuration_adv.h files. I tried to match my settings as closely as possible but I am unable to deploy the probe. G28 does not lower pin, haven't been able to try G29 since I can't home all axis. M280 has no affect. 

I just tried add this current BugFix to see if issue is addressed but I am getting errors while compiling. I had just replaced the Marlin_main.cpp. Is that how it's done? Were there other files that need to be updated? Sorry, new to the firmware end of things. 

My latest Configuration.h is attached
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/769064/Configuration.zip)

Thoughts and suggestions would be appreciated!!

2017-02-12 04:47 UTC, Roxy-3D commented
> I started yesterday to update the firmware on my FolgerTech 2020 i3. I have been using the firmware FT supplied. I had installed a BLTouch a month or so ago. Mechanically, everything seemed to work okay. I was having some problems with my prints starting too high (Z Offset not accounted for).

> While researching that issue and seeing all of the work you guys have been doing with the BLTouch, I figured I'd give updating my firmware a try!

So....   I absolutely love my FT i3-2020!   It is a really good machine.   The first version of the UBL code was developed on a FT i3-2020.   And the configuration.h and configuration_adv.h files are set up for that (my machine).    The only thing that is non-standard is I have the X-Min end stop on the left side instead of what their build directions state.   And of course, I've put a servo based probe leg on the extruder.    Other than that...   If you grab the code base at:  https://github.com/MarlinFirmware/Marlin/tree/devel-ubl  it will compile and run on your FT i3-2020.   

I'm working right now to move the code to RC-8's RCBugFix.   One of the things that will do is provide the simple BL-Touch support where you just say you have a BL-Touch and the right thing happens.   But right now...  at that link you would still have to set your servo angles at 10 degrees and 90 degrees.   

If you are willing to move to a development branch, I'll help you get it up and running on your FT 13-2020.   You will be impressed.   I get perfect adhesion across 100% of the bed 100% of them.   And I'm using the worst piece of glass I could find at a dollar store just to make sure the system is stressed.

2017-02-12 05:49 UTC, Bob-the-Kuhn commented
@DynamiteHack  - yes, please open a new issue so we can help you without muddying up the waters on this one.

When switching to a new revision/branch of Marlin firmware it's best to download the whole thing and then copy your machine specific info over.  Usually that just involves editing configuration.h & configuration-adv.h but might also involve editing your pins_YOUR_BOARD.h 

Did the BLTouch work before you moved to the new Marlin software?  

Which Marlin software did you switch to?

Issuing a M280 P0 S10 should deploy the probe and a M280 P0 S90 should stow it.  If that's not happening then we'll need to look at what pins have been assigned to the BLTouch's servo signal.

Your BLTouch setup looks good.

2017-02-12 07:13 UTC, merged

2017-02-12 07:34 UTC, DynamiteHack commented
Awesome! Thanks for the responses guys!

**@Roxy-3D** - I am very happy with my printer. I have my Xmin on the left also. I thought that's where it belonged!! LOL! That's where it was on my wooden Simple and I couldn't adjust to having it on the right!! I'll give that code a try here in a little while and yes, I'd love try out the development branch. 

I gotta say, I spent probably 6 hours reading different posts of yours and **@Bob-the-Kuhn**'s over the last day and a half and am amazed at the work you all are putting into this project. I've been wanting to learn more about how my printer works and was a little leary about diving into the firmware but I'm glad I did. 

**@Bob-the-Kuhn** - Thanks for the tip on using revised code. I plan on getting good at it!!

To answer your questions, my BLTouch mostly worked except I was having problems with my prints starting off the bed. I used startup codes to put the nozzle in the proper position for printing but I didn't want to use the band-aid permanently.

I am running 1.1.0-RC8

As far as pins go...we'll pick that up in the new issue I'll open after I try @Roxy-3D's code.

Thanks again!!

2017-02-14 12:29 UTC, thinkyhead commented
Ref: #5705

2017-08-17 14:02 UTC, tcm0116 commented
@Bob-the-Kuhn - First of all, I just wanted to say that this change has been great. However, I've noticed that there is still a dependency between the the feedrate and the accuracy of the probe/endstop. 

With interrupts enabled, the endstops are checked every 1 millisecond. My machine delta machine runs at 100 steps/mm, and the default `Z_PROBE_SPEED_SLOW` for delta machines is 100 mm/sec, which results in 10 steps per millisecond. With the endstops only being checked once per 10 steps, the resulting error of the probe can be as much as 0.1mm. The issue is that the error can vary between 0mm and 0.1mm depending on how the stepper and temperature ISRs are interacting that day.

One solution would be to adjust the `Z_PROBE_SPEED_SLOW` such that only one step is generated per millisecond when endstop interrupts are enabled (10 mm/sec in my case) or one step per 1.5 ms without endstop interrupts. It might be nice if this feedrate was automatically computed by Marlin, or at least a warning/error was generated when compiling if the feedrate is too high.

Another solution would be to run the endstop check in the stepper ISR during homing/probing. I'm not sure how expensive checking the endstops is, so this may not be feasible unless the feedrate is low enough.

Do you have any thoughts on this?

2017-08-17 16:55 UTC, Bob-the-Kuhn commented
Don't be afraid to change the defaults.  You're expected to tune these for your machine.

The speeds are in mm per minute.

I think you need some more info on the endstop detection system.

The recorded endstop position is at most one step beyond the first detection of the endstop signal.  

The endstops are checked every time the stepper ISR is run.  The stepper ISR runs once for every step unless you're running at a very high rate  (at least 2k steps per second). 

It takes two consecutive positive reads before the detection is declared valid and the current position is recorded (by the stepper ISR).

The "guaranteed" part is because of the 5mS pulse from the BLTouch.  If the detection method is too slow then the pulse can be missed which results in a head crash.  This is a problem only when running slow step rates.

There are two methods to guarantee detection when running slow step rates.

The first method was to make the stepper ISR run at least every 2mS (even if no steps were needed).

The second method uses a pin change interrupt for the first detection.  That initiates the 1 mS check rate to make sure we get two samples in during the 5mS pulse. The first stepper ISR after the initial detection records the position.

2017-08-17 20:49 UTC, tcm0116 commented
Thanks for the clarification. I was apparently missing the part that the endstops are already checked in the stepper ISR. 

I've been struggling with my first layer height being very inconsistent. Sometimes it's too high, and other times it drags the nozzle on the bed. I'm using a BLTouch, which should be pretty consistent. I'll keep investigations and see if I can figure it out.

2017-08-17 22:59 UTC, Bob-the-Kuhn commented
Please open a new issue.  That'll get you the needed help.