Implements REPROBE and REWIPE, using Nozzle::clean()
MarlinFirmware/Marlin pull request #5763
Opened 2017-01-31 04:37 UTC by hexane360

Implements the features described here: https://github.com/MarlinFirmware/Marlin/pull/3553

Logic works as follows:
-setup_for_endstop_or_probe_move() resets a global variable "attempt" to count probe attempts
-do_probe_move now returns bool. If the endstop is triggered before the end of the move, true/success is returned.
-attempt_probe now sits in between run_z_probe and do_probe_move. run_z_probe still controls fast/slow bumps, but attempt_probe now loops do_probe_move until success or failure, rewiping in-between if defined.

This PR also fixes a few bugs I found in functions that implement probe_pt, where both probe_pt and the caller function account for XY probe offset, causing the probe to be off in the opposite direction.

Please let me know if this fits the criteria discussed in the last PR, or what I need to change.

2017-01-31 08:12 UTC, Tannoo commented
```
Marlin_main.cpp:2128: error: variable or field 'attempt_probe' declared void
   static void attempt_probe(probe_speed) {
                                        ^
Marlin_main.cpp:2128: error: 'probe_speed' was not declared in this scope
   static void attempt_probe(probe_speed) {
                             ^
exit status 1
variable or field 'attempt_probe' declared void
```

2017-01-31 08:59 UTC, hexane360 commented
One caveat I currently see: All axes must be homed to auto-bed-level, but it's possible for other probe commands to execute and call attempt_probe() without a reliable z coordinate. I don't want to unnecessarily change behavior, but the Z-axis should really be homed for any probe failure detection. I'm not sure what the best way to go about this is. Maybe we should check homing `#if ENABLED(NOZZLE_PROBE` ?

2017-02-01 17:27 UTC, hexane360 commented
I've updated the code for G30 as follows:
`#if DEFINED(NOZZLE_PROBE) //needs z homing
  if (axis_unhomed_error(false, false, true)) return;
#endif`

This solves the problem of potentially running attempt_probe with Z unhomed.

2017-04-11 12:35 UTC, thinkyhead requested changes
Needs a rebase against the latest `RCBugFix`. You can remove the "fixes" for probe offsets, as they are not needed. Before merging, this should be squashed down to 1 or 2 commits.

2017-04-11 12:35 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
>        if (!position_is_reachable(pos, true)) {
`position_is_reachable` with `true` as the second parameter already subtracts these offsets.

2017-04-11 12:35 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +    float X_probe_location = code_seen('X') ? code_value_axis_units(X_AXIS) : X_current;
The coordinates given here are where to move the **_probe_**, not where to move the **_nozzle_**.

2017-04-11 12:35 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +          Y_current = Y_probe_location + sin(RADIANS(angle)) * radius;
…thus, here we're obtaining "where to put the nozzle" coordinates based on the "where to put the probe" coordinates, and these are the values tested against the movement limits.

2017-04-11 19:31 UTC, hexane360 commented
Alright, I've made the changes and melded it down into one commit.

2017-09-06 16:58 UTC, marcio-ao commented
@hexane360: Good work here! I made a similar change to our branch of Marlin, but didn't think of making a pull request for it. One difference is that I treat the number of rewipes as being per probe point, this saves a bit of memory by not having to have a global variable.

Here is my implementation, very similar to yours, but using a macro:

```
#define LULZBOT_NUM_REWIPES      2
#define LULZBOT_BED_PROBE_MIN   -3 // Limit on pushing into the bed

#define LULZBOT_PROBE_Z_WITH_REWIPE(speed) \
    /* do_probe_move returns true when it fails to hit an endstop, meaning we need to rewipe */ \
    for(int rewipes = 0; do_probe_move(LULZBOT_BED_PROBE_MIN, speed); rewipes++) { \
        if(rewipes >= LULZBOT_NUM_REWIPES) {          /* max of tries */ \
            SERIAL_ERRORLNPGM("PROBE FAIL CLEAN NOZZLE"); /* cura listens for this message specifically */ \
            LCD_MESSAGEPGM(MSG_ERR_PROBING_FAILED);   /* use a more friendly message on the LCD */ \
            BUZZ(25, 880); BUZZ(50, 0);               /* play tone */ \
            BUZZ(25, 880); BUZZ(50, 0); \
            BUZZ(25, 880); BUZZ(50, 0); \
            do_blocking_move_to_z(100, MMM_TO_MMS(Z_PROBE_SPEED_FAST)); /* raise head */ \
            stop();                                   /* stop print job */ \
            LCD_MESSAGEPGM(MSG_ERR_PROBING_FAILED);   /* stop changes the message... */ \
            return NAN;                               /* abort the leveling in progress */ \
        } \
        SERIAL_ERRORLNPGM(MSG_REWIPE); \
        LCD_MESSAGEPGM(MSG_REWIPE); \
        do_blocking_move_to_z(10, MMM_TO_MMS(speed)); /* raise nozzle */ \
        Nozzle::clean(0, 2, 0, 0);                    /* wipe nozzle */ \
    }
```

And in run_z_probe() I replaced the calls to do_probe_move() with the macro, like this:

```
      #if defined(LULZBOT_PROBE_Z_WITH_REWIPE)
      LULZBOT_PROBE_Z_WITH_REWIPE(Z_PROBE_SPEED_FAST);
      #else
      if (do_probe_move(-10, Z_PROBE_SPEED_FAST)) return NAN;
      #endif
```

2017-11-07 18:56 UTC, closed without merging