added support for the ZRIB V2.0 control board
MarlinFirmware/Marlin pull request #5888
Opened 2017-02-22 03:12 UTC by FATALHERMIT

theres still a few errors when compiling the lcd files something about uint_8, usec but it doesnt seem to be affecting anything

2017-02-22 03:22 UTC, FATALHERMIT commented
sorry i had forgotten to set the fan pins

2017-02-22 03:47 UTC, FATALHERMIT commented
the ramps pins seems to be overriding my settings, im working on it

2017-02-26 02:51 UTC, thinkyhead requested changes
Please make the requested changes, and then we'll review at the boards and pins files.

2017-02-26 02:51 UTC, thinkyhead commented on Marlin/boards.h
> -/**
Pleas use UNIX line endings.

2017-02-26 02:51 UTC, thinkyhead commented on Marlin/pins_ZRIB_V20.h
> +#include "pins_RAMPS.h"
This include is not needed (redundant).

2017-02-26 02:51 UTC, thinkyhead commented on Marlin/pins_ZRIB_V20.h
> +  #define E2_AUTO_FAN_PIN    ZRIB_V20_D9_PIN
You should override these instead:
```cpp
#undef ORIG_E0_AUTO_FAN_PIN
#undef ORIG_E1_AUTO_FAN_PIN
#undef ORIG_E2_AUTO_FAN_PIN
#undef ORIG_E3_AUTO_FAN_PIN
#define ORIG_E0_AUTO_FAN_PIN ZRIB_V20_D9_PIN
#define ORIG_E1_AUTO_FAN_PIN ZRIB_V20_D9_PIN
#define ORIG_E2_AUTO_FAN_PIN ZRIB_V20_D9_PIN
#define ORIG_E3_AUTO_FAN_PIN ZRIB_V20_D9_PIN
```

2017-02-26 02:51 UTC, thinkyhead commented on Marlin/pins_ZRIB_V20.h
> +  #define FAN_PIN        ZRIB_V20_D6_PIN
To override all general use of the usual `FAN_PIN` (D9) you should use this line instead, before the `#include pins_MKS_13.h` line:
```cpp
#define RAMPS_D9_PIN ZRIB_V20_D6_PIN
```
This allows the pin to be reassigned to a heater or other use according to the configuration.

2017-02-26 02:51 UTC, thinkyhead commented on Marlin/pins_ZRIB_V20.h
> +  #undef  SERVO1_PIN 6
`#undef` doesn't take a value. If you mean to redefine it, you should use both `#undef` and `#define`.

2017-02-26 02:51 UTC, thinkyhead commented on Marlin/pins_ZRIB_V20.h
> +  #define ZRIB_V20_D6_PIN 6
Two spaces indentation here, and on `ZRIB_V20_D9_PIN` below.

2017-02-26 02:51 UTC, thinkyhead commented on Marlin/pins.h
> -/**
Please fix the line endings in this file. You must use UNIX line endings.

2017-03-04 01:26 UTC, FATALHERMIT commented on Marlin/pins.h
> -/**
understood

2017-03-06 08:31 UTC, thinkyhead requested changes
Overall it looks simple enough. Please make the requested changes and it can be merged soon.

2017-03-06 08:31 UTC, thinkyhead commented on Marlin/pins_ZRIB_V20.h
> +#undef SERVO1_PIN
This line does nothing and can be removed.

2017-03-06 08:31 UTC, thinkyhead commented on Marlin/pins_ZRIB_V20.h
> +#undef ORIG_E3_AUTO_FAN_PIN
These three `#undef` lines also do nothing and can be removed.

2017-03-06 08:31 UTC, thinkyhead commented on Marlin/pins_ZRIB_V20.h
> +#include "pins_MKS_13.h"
A blank line above and below this `#include` line would make it better.

2017-03-06 08:31 UTC, thinkyhead commented on Marlin/pins_ZRIB_V20.h
> +#include "pins_MKS_13.h"
Add a header to the top of this pins file (copy and paste the header from `pins_MELZI.h`, for example).

2017-03-06 08:31 UTC, thinkyhead commented on Marlin/boards.h
> +#define BOARD_ZRIB_V20          504  // zrib V2.0 control board (Chinese knock off RAMPS replica)
Add a blank line below this one to separate it from the definition of `MB` below.

2017-03-08 04:10 UTC, FATALHERMIT commented
i'll try to work on it tomorrow

2017-03-12 06:55 UTC, FATALHERMIT commented
did the changes but had to start using E0_AUTO_FAN_PIN since it wouldnt work when i used ORIG_E0_AUTOFAN_PIN even pin debugging wasn't recognizing the D9 pin as an autofan when i used it. 
is it a bug or do i need to change something in the configuration files?

2017-03-18 21:17 UTC, Ma-P commented
IMHO is a nonsense to include pin_MKS_13.h and not directly pins_RAMPS.h, because the only thing which comes from  pin_MKS_13.h is #define MOSFET_D_PIN 7 .
And there is my version:

#ifndef BOARD_NAME
  #define BOARD_NAME "ZRIB v2"
  #define IS_RAMPS_EFB
#endif

#define MOSFET_D_PIN 6  //FAN_1_PIN

#include "pins_RAMPS.h"

#if HOTENDS == 2
  #undef HEATER_1_PIN
  #HEATER_1_PIN 7
#endif

2017-03-24 05:20 UTC, FATALHERMIT commented
so that should be it

2017-03-24 11:36 UTC, FATALHERMIT commented
@thinkyhead im ready to be inspected again

2017-03-28 14:22 UTC, lordgotham commented
hi sorry for my bad english but i'm french and don't understand all
i have a p802QR2 printer (zonestar) with 2 extruder and sensor with a zrib v2.2
i'm looking for a firmware for working my 2 extruder and sensor, i write many times zonestar but nobody help me.

could you explain me if you firmware can help me?
i see zrib v2

thank you

2017-04-21 06:39 UTC, FATALHERMIT commented
@lordgotham from i could tell from comparing your model to mine, which is a P802N or P802M, the P802 series seems to be very similar in terms of specs, so i guess you could try the firmware from the support site of site i bought it from [http://www.3dprintertutorial.org/eg-dual-upgrade](url) just be ready to press the emergency stop just in case

2017-05-22 14:45 UTC, empakoso commented
Thank you for your work on the ZRIB board.  I too have this board and would like to update it with your code.  Do you have a working copy of the Marlin fw for your EG printer?  I believe I own the same printer you referenced above. http://3dprintertutorial.org/prusa-i3-with-auto-level-and-zrib-card-tutorial

I would like to work out some of 'my' bugs in 1.1.1 using the new volumemetric, filament width sensor, and linear advance features.  However before I do that, I don't like my modifications I made to the motherboard pins.  I prefer a more professionally coded, approach.  

I've also added a diode laser as "T1" and would want to further that modification, but first want to correct my base fw, the motherboard.

I am looking forward to having this merged.

2017-06-02 00:57 UTC, closed without merging

2017-06-02 21:55 UTC, thinkyhead commented
Merged at #6932.