merge in anet board support for A6/A8
MarlinFirmware/Marlin pull request #5978
Opened 2017-03-06 22:38 UTC by trivalik

support for anet printer

2017-03-31 04:05 UTC, thinkyhead requested changes
Several changes are needed for this PR to be accepted.
Please rebase, update, and squash at your earliest convenience!

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/Conditionals_LCD.h
> +
We already have these covered:
```cpp
// Set encoder detents for well-known controllers
#if ENABLED(miniVIKI) || ENABLED(VIKI2) || ENABLED(ELB_FULL_GRAPHIC_CONTROLLER) \
 || ENABLED(BQ_LCD_SMART_CONTROLLER) || ENABLED(LCD_I2C_PANELOLU2) || ENABLED(REPRAP_DISCOUNT_SMART_CONTROLLER)
  #ifndef ENCODER_PULSES_PER_STEP
    #define ENCODER_PULSES_PER_STEP 4
  #endif
  #ifndef ENCODER_STEPS_PER_MENU_ITEM
    #define ENCODER_STEPS_PER_MENU_ITEM 1
  #endif
#endif
```

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/pins_ANET_10.h
> +#define LED_PIN -1
`#undef LED_PIN` takes care of this. No need to set it to -1.

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/pins_ANET_10.h
> +		#undef BTN_EN1
Please use spaces only for indentation. No tabs!

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/temperature.cpp
> +      {
Opening brace should be at the end of the previous line. Please consult our [Coding Standards](https://github.com/MarlinFirmware/Marlin/wiki/DNE-Coding-Standards).

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/temperature.h
> +#ifdef ADC_KEYPAD
Please indent this `#ifdef` and its `#endif` by 4 spaces.

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/ultralcd.cpp
> +        #if ENABLED(REPRAPWORLD_KEYPAD) && !ENABLED(ADC_KEYPAD)
`DISABLED` is preferred over `!ENABLED`.

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/ultralcd.cpp
> +  #if ENABLED(SDSUPPORT)
[Indentation](https://github.com/MarlinFirmware/Marlin/wiki/DNE-Coding-Standards).

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/ultralcd.cpp
> +          || (currentScreen == lcd_control_volumetric_menu)
No. Simply no. Don't add a block checking for all these `currentScreen` values. Whatever you're trying to do, find a better way.

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/ultralcd.cpp
> +          if (buttons_reprapworld_keypad&EN_REPRAPWORLD_KEYPAD_DOWN)
Please [pad all operators with spaces](https://github.com/MarlinFirmware/Marlin/wiki/DNE-Coding-Standards), including binary operators.

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/ultralcd.cpp
> +      #endif
This whole block should be indented by 2 spaces.

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/ultralcd.cpp
> +            if ((newbutton_reprapworld_keypad > 0) && (newbutton_reprapworld_keypad <= 8))
No need for pedantic parentheses. This is preferred:
```cpp
if (newbutton_reprapworld_keypad > 0 && newbutton_reprapworld_keypad <= 8) { . . .
```

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/ultralcd.h
> +      #define REPRAPWORLD_KEYPAD_MOVE_X_LEFT  (buttons_reprapworld_keypad & EN_REPRAPWORLD_KEYPAD_LEFT)
Since these defines are identical to the original, just put them back where they were above.

2017-03-31 04:05 UTC, thinkyhead commented on Marlin/ultralcd.cpp
> +
Please apply [the correct formatting](https://github.com/MarlinFirmware/Marlin/wiki/DNE-Coding-Standards).

2017-03-31 15:04 UTC, benlye commented
@trivalik, let me know if you want/need any help with this PR.  A couple of people have submitted various PRs for the Anet board and ADC encoder, but nothing has been up to being merged yet.  I have an A8 and have both the ADC keypad/LCD and the A6 RepRapDiscount Full Graphic Smart Controller so can build and test for both.

To be honest, it may be easier to close this PR and submit one PR just to add the board and pins definitions, then another for the code to make the ADC buttons work.

2017-04-03 18:35 UTC, JohnnyTheOne commented
A6 only needs the board Anet

2017-04-14 07:49 UTC, trivalik commented
I changed much as possible, just the "currentScreen ==" stuff is open. Maybe can somebody help me with this.

Is still "Bilinear leveling on Delta is broken" the case?

I try to fix the conflicts next days.

2017-04-14 09:55 UTC, trivalik commented
I rebase now. I fixed also the softspi.h, it was containing invalid preprocessor directive. But anyway it was not building for me, so I add a #if to temperature.cpp around spi.h.

2017-04-15 11:31 UTC, trivalik commented
Hi,


I rebased it to current, maybe you can check if the keys for the LCD are still working.


Best Regards

Trivalik


________________________________
Von: benlye <notifications@github.com>
Gesendet: Freitag, 31. März 2017 17:04
An: MarlinFirmware/Marlin
Cc: Trivalik; Mention
Betreff: Re: [MarlinFirmware/Marlin] merge in anet board support for A6/A8 (#5978)


@trivalik<https://github.com/trivalik>, let me know if you want/need any help with this PR. A couple of people have submitted various PRs for the Anet board and ADC encoder, but nothing has been up to being merged yet. I have an A8 and have both the ADC keypad/LCD and the A6 RepRapDiscount Full Graphic Smart Controller so can build and test for both.

To be honest, it may be easier to close this PR and submit one PR just to add the board and pins definitions, then another for the code to make the ADC buttons work.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/MarlinFirmware/Marlin/pull/5978#issuecomment-290737461>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ADAJ97sYv2b78-aVPm5tEkKcNMsV0srvks5rrRYSgaJpZM4MUyt8>.

2017-04-16 19:15 UTC, trivalik commented on Marlin/ultralcd.cpp
> +
Please review again, just the point with "currentScreen ==" I am not sure with. It looks like to detect when to press and unpress a key, Maybe somebody with an A8 can check this.

2017-04-17 21:27 UTC, trivalik commented
@benlye can you try the current version.

I am not sure how to get out of the "Changes requested" thing.

2017-04-21 17:18 UTC, benlye commented
@trivalik, you should probably sync up with @oderwat, who maintains the [SkyNet3D Marlin fork](https://github.com/SkyNet3D/Marlin/).  He's just done a bunch of work on the ADC keypad code.  I no longer use the ADC keypad, so it's difficult for me to test most of this now.

2017-04-21 18:19 UTC, oderwat commented
Yep... I am actually pretty close to create a PR for the ANet printers. Recently I added accelerated input for the stock displays keypad and got rid on some more "specialities" to make it smother to merge it with the Marlin codebase.

2017-04-21 21:17 UTC, trivalik commented
@oderwat in case I have a few optimizations, as you can see in this PR, against what branch name should I create a pull request into your fork?

2017-04-21 21:33 UTC, oderwat commented
@trivalik Please for SkyNet3D/Marlin and use SkyNet3D-Base for that purpose which I just created for you. I usually update SkyNet3D-Devel frequently by rebasing against new RCBugFix. Because of that I often force push it.

Actually all the Anet related changes are just one commit and if I need to add stuff I rebase and reorder commits to fix stuff. I just need to clean up some few things to create a PR from that. I can cherry pick optimisations you do from your branch if needed.

2017-04-23 12:42 UTC, trivalik commented
@oderwat I was guessing that ADC_KEYPAD_PIN is always defined, but on building with my sanity change below, show me that this is not true. So, that I do not understand the change in temperature.cpp with Prepare_ADC_KEY and Measure_ADC_KEY. I was guessing it has something todo with the key next to the LCD, but in temperature.cpp is should be just temperature stuff. any hint would be appreciated.

  #if ENABLED(ADC_KEYPAD) && !PIN_EXISTS(ADC_KEYPAD_PIN)
    #error "ADC_KEYPAD to be a valid pin for ADC_KEYPAD_PIN. Please update your configuration."
  #endif

2017-04-24 11:12 UTC, oderwat commented
@trivalik the pin is only needed if you have the ADC_KEYPAD as with the ADC_KEYPAD_LCD of the A8. I have and test with three different displays on my A8.

In temperature.cpp is not only temperature stuff. For example there is also the filament width sensor code and so is the ADC_KEYPAD. Mainly because it is a good place to query the analog data which is needed to calculate the button pressed and works similar to the temperature and other sensors. The latest change by Marlin devs made this case/loop construct easier to extend too. I guess the naming of the file could be changed but this is something nobody using git likes a lot usually :)

2017-04-28 19:13 UTC, erm2587 commented
Hi all,

I'm very interested on helping here, I also have an Anet A8. So if here is something I can do for speeding up this pull request, just tell me ;-)

Thank you

2017-04-28 21:40 UTC, oderwat commented on Marlin/boards.h
> +#define BOARD_ANET_10           621  // Anet v1.0
I still prefer the 69. Any reason why not to use that?

2017-04-28 21:43 UTC, oderwat commented
Well. What I dislike about this PR is that much of the code here is my personal work and I was going to add a PR as soon as I am done with finishing it.

2017-04-28 21:47 UTC, oderwat commented
@erm2587 the original ANet fork is here: https://github.com/SkyNet3D/Marlin/

2017-04-29 12:04 UTC, trivalik commented
I see this same like oderwat. So I hope he create very soon a PR. I close this now.

2017-04-29 12:04 UTC, closed without merging