UBL - add rectangular probing for G29 P1
MarlinFirmware/Marlin pull request #6132
Opened 2017-03-27 04:20 UTC by Bob-the-Kuhn

I was tired of waiting for the circular probing so I grabbed the bilinear G29 probing code & combined it with the existing G29 P1 code.

I added flags to the Configuration.h files to control which one get executed.

2017-03-27 13:41 UTC, Roxy-3D commented
I have several questions:
- I was having problems answering this question from the diff.   If #define CIRCULAR_PROBING  is turned off, does all the new grid code just disappear?   If so, that makes it much 'safer' to merge without extensive testing.   
- Would it make sense to break out the probe_entire_mesh() function and its support functions like find_closest_mesh_point_of_type() into its own file?   That would give us a cleaner organization to merge this into.
- I haven't looked at it...  But I presume we can alter the rectangular grid probing code easily to handle the round beds of Delta's.   Bringing UBL up on Delta's is going to happen as soon as everything else settles down.   
- How bad are the 'Conflicts' GitHub is complaining about.  Is that because I have an open Pull Request for the G29 code?   If so...   How do I back off so these conflicts disappear?    If that is what is happening...   We will probably need to merge this ASAP just to get it out of the way of other G29 changes (or vice versa depending upon your perspective).

2017-03-27 14:23 UTC, Bob-the-Kuhn commented
> I was having problems answering this question from the diff. If #define CIRCULAR_PROBING is turned on, does all the new grid code just disappear? If so, that makes it much 'safer' to merge without extensive testing.

Yes, it just disappears.

> Would it make sense to break out the probe_entire_mesh() function and its support functions like find_closest_mesh_point_of_type() into its own file? That would give us a cleaner organization to merge this into.

What ever you're happy with is fine by me.

> I haven't looked at it... But I presume we can alter the rectangular grid probing code easily to handle the round beds of Delta's. Bringing UBL up on Delta's is going to happen as soon as everything else settles down.

It can't handle deltas.  It assumes each row/column is a fixed length.

It's probably better to rename the flags.  How about the following. 
```
UBL_PROBE_DELTA_RECTANGULAR  // handles all types of printers
UBL_PROBE_RECTANGULAR ONLY  // faster but doesn't work for deltas
```

It's also a good idea to make the enable say:
`#elif ENABLED(UBL_PROBE_RECTANGULAR ONLY) && !ENABLED(DELTA)`

> How bad are the 'Conflicts' GitHub is complaining about. Is that because I have an open Pull Request for the G29 code? 

I'll go look at your PR.  I thought the PRs were independent but maybe not.  I'll fix this one.

2017-03-27 14:34 UTC, Roxy-3D commented
>> I was having problems answering this question from the diff. If #define CIRCULAR_PROBING is turned on, does all the new grid code just disappear? If so, that makes it much 'safer' to merge without extensive testing.
> Yes, it just disappears.

OK!   Good!   That makes more 'comfortable' to do the merge without lots of testing.

>> Would it make sense to break out the probe_entire_mesh() function and its support functions like find_closest_mesh_point_of_type() into its own file? That would give us a cleaner organization to merge this into.
> What ever you're happy with is fine by me.

I hate to make extra work.   But G29 is starting to get big.   If we can break out the P1 code into a new file called something like 'UBL_G29_Auto_Probing.cpp'  that would be good.

>> I haven't looked at it... But I presume we can alter the rectangular grid probing code easily to handle the round beds of Delta's. Bringing UBL up on Delta's is going to happen as soon as everything else settles down.
> It can't handle deltas. It assumes each row/column is a fixed length.

I'm not too worried about this.   Either we can limit the probing so it doesn't go out too far from the center of the bed or we can put in Travis checks that don't allow rectangular probing with Delta's.   But my inclination would be to just put a few conditional lines of code in that keep it from going off the bed in the case of Delta's.   We don't need to do that now.   I'll do that when I start bringing it up on Delta's.

> It's probably better to rename the flags. How about the following.
```cpp
UBL_PROBE_DELTA_RECTANGULAR  // handles all types of printers
UBL_PROBE_RECTANGULAR ONLY  // faster but doesn't work for deltas
```
I don't like having 'DELTA' in the name of something that is intended for all printer types.  That is going to confuse people.    For now...   how about we just change the name
```cpp
#define CIRCULAR_PROBING
``` 
to be UBL specific with
```cpp
#define UBL_CIRCULAR_PROBING
```
>> How bad are the 'Conflicts' GitHub is complaining about. Is that because I have an open Pull Request for the G29 code?
> I'll go look at your PR. I thought the PRs were independent but maybe not. I'll fix this one.
Just tell me when things are ready (again) and I'll try to get out of the way.

2017-03-27 19:17 UTC, Roxy-3D commented
On my previous merge...   I could not figure out what was causing the conflicts.   I even tried deleting the new changes and then replacing them.   That didn't work.   

What did work for me was to abandon the Pull Request I had been working in, and start with a fresh fork.   I then put my changes into that fork and magically everything went smoothly.    If you get tired of fighting this conflict thing...    You might try setting your current directory aside (so you can still get to it).   And then do a fresh fork and clone.

2017-03-28 05:12 UTC, Tannoo commented
I'm trying to test this and it keeps telling me `?Error: Attempt to probe off the bed.`
I added some echos to tell me where it wants to probe.
```
          if (xProbe < MIN_PROBE_X || xProbe > MAX_PROBE_X || yProbe < MIN_PROBE_Y || yProbe > MAX_PROBE_Y) {
            SERIAL_PROTOCOLLNPGM("?Error: Attempt to probe off the bed.");
            SERIAL_ECHOLNPAIR("xProbe: ", xProbe);
            SERIAL_ECHOLNPAIR("yProbe: ", yProbe);
            ubl_has_control_of_lcd_panel = false;
            goto LEAVE_RECTANGULAR;
          }
```
Well, it says:
```
?Error: Attempt to probe off the bed.
xProbe: 199.00
yProbe: 1.00
```
It doesn't seem to care about probe offsets?

2017-03-28 06:24 UTC, Bob-the-Kuhn commented
The current code assumes all points are probeable.

I'll have new code in the PR tomorrow.  It uses the is_reachable code to determine which points to skip.  

I want to see how it handles a round bed before I commit it.

2017-03-29 11:31 UTC, thinkyhead requested changes
With the line endings fixed, this can be reviewed further!

2017-03-29 11:31 UTC, thinkyhead commented on Marlin/UBL_G29.cpp
> -/**
This file is showing as entirely replaced because your line endings are not Unix-style. Once fixed, this will show up correctly.

2017-03-29 23:56 UTC, Bob-the-Kuhn commented on Marlin/UBL_G29.cpp
> -/**
If the entire file is not Unix style then we've run into a git bug.  I do all my editing on a Windows machine.  Git is supposed to translate the line ending based on the target operating system.

I have run into some files where the line endings are a mix of Windows and Unix line endings.  Sometimes that causes compiler problems.

2017-03-30 00:24 UTC, Blue-Marlin commented on Marlin/UBL_G29.cpp
> -/**
https://help.github.com/articles/dealing-with-line-endings/

2017-03-30 00:46 UTC, Bob-the-Kuhn commented
Just uploaded a much improved version.  

The main improvement was adding a UBL specific "is_reacheable" routine.  It is used to determine if the probed point is within the mesh limits and if the probe point is reachable.  If both are true then the point is probed.

Handles both rectangular and circular beds.

Handles situations where the travel limits are wider than the mesh area.

Rectangular:
1. assumes the travel area is set by the X_MIN_POS ... defines 
2. assumes the mesh area is set by the UBL_MESH_MIN_X ... defines
3. assumes the UBL_MESH_INSET has already been incorporated into the UBL_MESH_MIN_X ... defines

Circular:
1. assumes DELTA_RADIUS minus UBL_MESH_INSET is the same as the UBL_MESH_MIN_X ... defines
2. assumes travel area is the same as DELTA_RADIUS unless DELTA_TRAVEL_RADIUS is defined.  DELTA_TRAVEL_RADIUS is something I just made up.

The rectangular & circular assumptions can be easily modified.  Let me know what makes sense.

----

Speed - G29 P1 - 9x9 grid includes G28
Rectangular probing:  4:26
Circular probing: 6:26

**Since this is only a 30% improvement in speed, is it worth continuing this PR?**

----

The circular bed is placed within a rectangular grid.  Do we need to mark the points outside the bed so that they're not used when doing manual probing?

Right now the routine just leaves them as NAN.  There's a convenient place for code to mark these points as special.

----

The file UBL_G29.cpp debug just has all my debug prints in it.  Only use it if you're trying to debug it.

2017-03-30 02:00 UTC, Bob-the-Kuhn commented
The line ending issue is still there and git is still throwing in extraneous conflicts.

I'm going to open a new branch and a new PR to see if that resolves these issues.

2017-03-30 02:41 UTC, Bob-the-Kuhn commented
This PR has been replaced by PR #6161.

Hopefully the new PR doesn't have the git issues.

2017-03-30 02:41 UTC, closed without merging

2017-03-30 02:43 UTC, Roxy-3D commented
@Bob-the-Kuhn    This is a little late to be throwing out this idea...   But UBL uses the find_closest_mesh_point_of_type() function to determine the next point to probe or edit for almost all of its functions.   What if you just supplied a new find_next_point() routine.   Or...  Maybe you added a new type.  Instead of looking for REAL or INVALID or whatever...   You specified a type of RECTANGULAR_GRID.    That would hook in fairly cleanly?    

I have a hunch that some people would prefer a rectangular grid pattern for the editing and not just the probing.    

Like I say...   It is a little late for these kind of suggestions...

2017-03-30 03:08 UTC, Roxy-3D commented
So...   At: https://help.github.com/articles/dealing-with-line-endings/

It says:
```cpp
Per-repository settings

Optionally, you can configure the way Git manages line endings on a per-repository basis by configuring a special .gitattributes file. This file is committed into the repository and overrides an individual's core.autocrlf setting, ensuring consistent behavior for all users, regardless of their Git settings. The advantage of a .gitattributes file is that your line configurations are associated with your repository. You don't need to worry about whether or not collaborators have the same line ending settings that you do.
```
Shouldn't we configure the Marlin repository to always use \n and just be done with this problem????