Updated
MarlinFirmware/Marlin pull request #6370
Opened 2017-04-17 07:19 UTC by Tannoo

Corrections and updates from RCBugFix.

2017-04-18 08:12 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +      if (wait_for_heatup && !wants_to_cool) {
`wait_for_heatup` is always set during the loop, so can be omitted here.

2017-04-18 08:17 UTC, thinkyhead requested changes
Various formatting and logical changes are needed. I will see about patching this up in a day or two.

2017-04-18 08:17 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +        if (blue != old_blue) set_rgb_color(255, 0, blue, 0, 0, 1);  //Start transitioning to Red
These lines resurrect the bad logic I pointed out earlier. Please just extend add the new parameters to the existing `set_led_color` line. Let's preserve the `set_led_color` function name and keep it as the main setter.

2017-04-21 21:26 UTC, Tannoo commented on Marlin/Marlin_main.cpp
> +      if (wait_for_heatup && !wants_to_cool) {
Done

2017-04-21 21:27 UTC, Tannoo commented on Marlin/Marlin_main.cpp
> +        if (blue != old_blue) set_rgb_color(255, 0, blue, 0, 0, 1);  //Start transitioning to Red
Changed it to set_led_color.

2017-04-30 22:47 UTC, thinkyhead requested changes
minor tweak to the config additions

2017-04-30 22:47 UTC, thinkyhead commented on Marlin/Configuration.h
> +      /* Strip specific items */
delete this line and the blank line above it

2017-04-30 22:48 UTC, thinkyhead commented
This is on hold until after release. We should revisit this and see about making it a sub-feature of the existing RGB LED stuff instead of making it a whole separate feature.

2017-05-01 20:12 UTC, Tannoo commented
Well, my end doesn't show any conflicts. Online OR local.
I click on the `Resolve conflicts` button and I can see the conflicts. That is the only place I can see them and the online editor doesn't work for me.

Let me get this caught up with all the recent changes.

2017-05-01 20:16 UTC, Tannoo commented
There we go.

2017-05-01 20:17 UTC, Tannoo commented on Marlin/Configuration.h
> +      /* Strip specific items */
Done.

2017-05-10 01:18 UTC, Tannoo commented
Yeah, I found this issue also and is fixed in this PR.

http://forums.reprap.org/read.php?415,766651

2017-05-12 18:22 UTC, closed without merging