Silvergate board
MarlinFirmware/Marlin pull request #6427
Opened 2017-04-22 17:06 UTC by android444

Add new board

https://github.com/android444/Silvergate

2017-04-30 22:21 UTC, thinkyhead commented
The added example configurations will need to be re-done based on the current (slightly reorganized) configurations.

2017-04-30 22:21 UTC, thinkyhead requested changes
Some changes needed…

2017-04-30 22:21 UTC, thinkyhead commented on Marlin/pins_SILVER_GATE.h
> +/**
```cpp
/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

```

2017-04-30 22:21 UTC, thinkyhead commented on Marlin/pins_SILVER_GATE.h
> + #endif
Please keep indentation consistent. See http://marlinfw.org/docs/development/coding_standards.html

2017-04-30 22:21 UTC, thinkyhead commented on Marlin/pins_SILVER_GATE.h
> +	        #define BEEPER_PIN 29
Please replace all tabs with spaces. http://marlinfw.org/docs/development/coding_standards.html

2017-04-30 22:21 UTC, thinkyhead commented on Marlin/pins_SILVER_GATE.h
> +  #define BOARD_NAME "SILVER GATE"
Is this an acronym? Otherwise, "Silver Gate" is better.

2017-05-01 11:12 UTC, android444 commented
I found a bug.
I do not know how to do a new pull request.
The problem is with the heatbed.

2017-05-17 06:53 UTC, android444 commented
What are the required corrections?

2017-10-06 20:49 UTC, android444 commented
I'll do it again.

2017-10-06 20:49 UTC, closed without merging