Update language_cz.h for new translations
MarlinFirmware/Marlin pull request #6465
Opened 2017-04-26 23:05 UTC by clexpert

2017-04-27 06:19 UTC, Kaibob2 requested changes

2017-04-27 06:19 UTC, Kaibob2 commented on Marlin/language_cz.h
> +#define MSG_PREHEAT_1_END                   MSG_PREHEAT_1 _UxGT(" Tryska")
MSG_PREHEAT_1_END should be translated to "End" or "finished".
I guess "Tryska" means "Nozzle"

2017-04-27 06:19 UTC, Kaibob2 commented on Marlin/language_cz.h
> +#define MSG_PREHEAT_2_END                   MSG_PREHEAT_2 _UxGT(" Tryska")
MSG_PREHEAT_2_END should be translated to "End" or "finished".
I guess "Tryska" means "Nozzle"

2017-04-27 08:04 UTC, Kaibob2 commented on Marlin/language_cz.h
> +#define MSG_PREHEAT_1_END                   MSG_PREHEAT_1 _UxGT(" Tryska")
Uhh, dammit, complete misunderstanding on my side. I derived it from language_en.h and interpreted MSG_PREHEAT_1_**END** as "finished" and not as "hotend".
Sorry for that.

2017-04-27 08:05 UTC, Kaibob2 commented on Marlin/language_cz.h
> +#define MSG_PREHEAT_2_END                   MSG_PREHEAT_2 _UxGT(" Tryska")
Uhh, dammit, complete misunderstanding on my side. I derived it from language_en.h and interpreted MSG_PREHEAT_1_**END** as "finished" and not as "hotend".
Sorry for that.

2017-04-27 15:35 UTC, clexpert reviewed
@Kaibob2 OK 😄 😄 😄 I have reverted the changes back to "hotend".

2017-04-27 15:35 UTC, clexpert commented on Marlin/language_cz.h
> +#define MSG_PREHEAT_2_END                   MSG_PREHEAT_2 _UxGT(" Tryska")
@Kaibob2 You are right. Thanks. I thought that "end" is abbreviation of "hotend" in this sense.

2017-04-28 18:47 UTC, Roxy-3D commented
Thank You!

2017-04-28 18:47 UTC, merged