M701 and M702 support from LCD and Gcode
MarlinFirmware/Marlin pull request #6493
Opened 2017-04-29 00:58 UTC by q3ok

From the M600 I've created the M701 and M702 support, and I've added it as new menu items to Prepare menu. There is no translations, its only in en language for display. The filament load are using still the screen from M600 with "Resume print" message, it has to be changed also.

2017-04-29 12:05 UTC, thinkyhead commented
Overall the implementation looks good (though I have yet to review it fully). Note that all new features must be made optional and disabled by default, so you'll need to add a new configuration option to make it possible to enable/disable this feature, and set it disabled.

2017-04-29 12:06 UTC, thinkyhead requested changes
Some spacing changes requested…

2017-04-29 12:06 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +	  if (thermalManager.tooColdToExtrude(active_extruder)) {
Please do a global search and replace to replace tabs with spaces.

2017-04-29 12:06 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +    /**
Remove extra leading space(s) here.

2017-04-29 19:47 UTC, q3ok commented on Marlin/Marlin_main.cpp
> +	  if (thermalManager.tooColdToExtrude(active_extruder)) {
Global tabs has been replaced with spaces, I believe that i didn't missed any

2017-04-29 19:47 UTC, q3ok commented on Marlin/Marlin_main.cpp
> +    /**
Spaces removed

2017-04-29 19:48 UTC, q3ok commented
The option FILAMENT_LOADUNLOAD_SUPPORT has been added in Configuration_adv

2017-05-02 04:33 UTC, tcm0116 commented
@q3ok I recently submitted a pull request (https://github.com/MarlinFirmware/Marlin/pull/6407) that deals with the Filament Reload and Pause features. We might want to coordinate since this one is related to that group.

2017-05-07 20:44 UTC, q3ok commented
@tcm0116 I am not sure if even the pause feature should be unified with filament change. IMO that should be two different options, but I can agree that M600 can be splitted into at least two functions, as well to use with M701, M702 and M125.
After few days of using the M701 and M702 made from M600 i found that there is a bug after filament load, which prevents to start any print - I didn't found yet the reason.

2017-05-08 14:46 UTC, tcm0116 commented
@q3ok By unify, I meant that it would make sense to have them share a set of common functions in the code, but still use the respective M codes. This would prevent having very similar code in several different places that has had small changes made to it.

2017-05-08 21:22 UTC, tcm0116 commented
@q3ok In my setup, I'm using an E3D Cyclops hotend, and they actually recommend feeding both filaments cold as far as possible before heating up the nozzle. As such, it would be nice to have the option to load the filament with the nozzle cold, and possibly even the option of feeding both extruders simultaneously. This would then require that the hotend be heated up and then the filament loaded the rest of the way. Thoughts on this?

2017-07-02 07:12 UTC, thinkyhead approved these changes

2017-07-02 07:12 UTC, thinkyhead commented
#7107 supplants this PR…

2017-07-02 07:12 UTC, closed without merging