UBL: G26 minor improvements
MarlinFirmware/Marlin pull request #6511
Opened 2017-04-30 20:56 UTC by Bob-the-Kuhn

Adding startup notice & update host temperatures while waiting

Right now G26 doesn't send a notice to the host that it's running.  It's
not until the heaters are at temperature that you know for sure if it's
running or not.

Added host temperature prints so that someone watching the host
interface will see the temperatures change during the warm up period.
Updates are sent every 5 seconds.

2017-04-30 21:11 UTC, thinkyhead commented on Marlin/G26_Mesh_Validation_Tool.cpp
> +    SERIAL_ECHOLNPGM("G26 command started.  Waiting on heater(s).");
"Waiting for heater(s)" will translate better to other languages.

2017-04-30 21:13 UTC, thinkyhead requested changes
millis changes

2017-04-30 21:13 UTC, thinkyhead commented on Marlin/G26_Mesh_Validation_Tool.cpp
> +            if (millis() > next) {
You must use the `PENDING(millis(), next)` macro here.

2017-04-30 21:13 UTC, thinkyhead commented on Marlin/G26_Mesh_Validation_Tool.cpp
> +      if (millis() > next) {
Use `PENDING(millis(), next)` here also.

2017-04-30 21:14 UTC, thinkyhead commented on Marlin/G26_Mesh_Validation_Tool.cpp
> +          next = millis() + 5000;
For consistency:
```
next = millis() + 5000UL;
```

2017-04-30 21:16 UTC, thinkyhead commented
If the problem here is that the host needs to know that the firmware is busy, the solution is to use `KEEPALIVE_STATE(IN_PROCESS);`. Then afterward, `KEEPALIVE_STATE(IN_HANDLER);`

2017-05-01 01:17 UTC, Bob-the-Kuhn commented
All the changes have been implemented.

The issue is the user doesn't currently see the temperatures changing via the host interface.  He can see them change via the LCD.

2017-05-02 21:06 UTC, thinkyhead approved these changes

2017-05-02 21:06 UTC, merged

2017-05-02 21:06 UTC, thinkyhead commented
Makes sense!