Add configurable action command to send when printer is killed
MarlinFirmware/Marlin pull request #7217
Opened 2017-07-02 17:55 UTC by benlye

Sends user-defined string as action command when printer is killed.

Spawned from conversation in #7137, where a couple of people thought that informing a connected host that the printer has been killed in a user-configurable, language agnostic, way would be useful.

I'm sure there are other action commands which it would be useful for the printer to send, but a 'kill' action is the one which seems most useful to me.  With that in mind, I couldn't decide if the variable should be `KILL_ACTION`, which groks easier, or `ACTION_KILL`, which lends itself to being in a list of other action definitions.  I don't feel strongly either way.

2017-07-02 18:35 UTC, Roxy-3D commented
USER_SPECIFIED_ACTION_AT_KILL   leaves very little doubt about what is being specified and when it will be invoked.   For something as important as this...  It doesn't bother me to have a slightly longish name.

2017-07-02 23:54 UTC, fiveangle commented
But I do see how having all ACTION_* strings in a common location useful, and prefixing with "USER_SPECIFIED_ACTION" doesn't really lend itself well toward finding if someone is looking for "ACTION" items (which is what other host software like Repeteir and Octoprint lump them into).

I do like ACTION_AT_KILL (since ACTION_AT_SUICIDE as per some existing internal values seems a bit melodramatic ;)

2017-07-03 02:12 UTC, Roxy-3D commented
Yes.  You are correct...   

I don't really care what the name is.  But I want it very obvious what it means when it shows up in the code some where.   Let's not skimp on characters for the name just to make it short.  I prefer something like this is very very obvious!      

And if the user presses the Kill button on the LCD Panel, it isn't a 'Suicide'.  The firmware didn't kill itself.

2017-07-03 07:29 UTC, thinkyhead requested changes
Two minor changes needed…

2017-07-03 07:29 UTC, thinkyhead commented on Marlin/Configuration_adv.h
> +//#define KILL_ACTION "poweroff"
Please clone these lines to the same position in all `Configuration_adv.h` files in example_configurations. The easiest way is to replace the unique lines that precede this with those same lines, plus this.

2017-07-03 07:29 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +  #endif
Please use this instead to save on SRAM:
```cpp
SERIAL_ECHOLNPGM("//action:" KILL_ACTION);
```

2017-07-03 08:14 UTC, benlye commented on Marlin/Configuration_adv.h
> +//#define KILL_ACTION "poweroff"
Will do - wanted to have the conversation about the parameter name before I went and edited a bunch of files.  ACTION_AT_KILL seems good to me.  Do you have a preference?

2017-07-03 13:47 UTC, benlye commented
Not to be pedantic, but `ACTION_ON_KILL` sounds better to me than `ACTION_AT_KILL`, and I think that syntax will work well for any future action commands.  I'm ready to update the PR with @thinkyhead's changes and the revised name as soon as there is consensus.

2017-07-03 18:04 UTC, fiveangle commented
> ACTION_ON_KILL sounds better to me than ACTION_AT_KILL

Agreed.  But it looks like Scott doesn't want to change the string name throughout ?  Maybe make the change as he describes for now, and if the action commands take off, we can revisition renaming so all actions are prefixed with "ACTION_" at a later time ?

2017-07-03 18:12 UTC, fiveangle commented
> But I want it very obvious what it means when it shows up in the code some where. 

To @Roxy-3D 's point, the ACTION is a host feature class that probably deserves some for of documentation on the wiki.  @benlye - do you have an idea on where you could inject this info ?  Also, your new Mcode probably needs an entry ?

2017-07-03 22:49 UTC, benlye commented
I've changed the serial out method to `SERIAL_ECHOLNPGM`, made the modification to all the configuration_adv.h example files, and in the absence of any other feedback I went ahead and changed the parameter name to `ACTION_ON_KILL`.

2017-07-04 21:41 UTC, thinkyhead commented
This is a great contribution, simple as it is. Thanks!

We ought to also add a "`CAP:ACTIONS:1`" string to the `M115` output when this is enabled.

2017-07-04 21:44 UTC, thinkyhead approved these changes

2017-07-04 21:44 UTC, merged