Add GFX to UBL mesh edit screen
MarlinFirmware/Marlin pull request #7645
Opened 2017-09-10 17:38 UTC by cdedwards

This adds the up/down and rotation graphics to the mesh editing screen of UBL.
Shamelessly stolen from  marcio-ao

2017-09-10 18:15 UTC, Roxy-3D commented
@cdedwards    Probably we should make a small change.  It would be good to add a SanityCheck.h condition to look for AUTO_BED_LEVELING_UBL_GFX being enabled with a non-graphics LCD Panel.

It maybe we can define similar custom characters for the 20x4 LCD Panels and do the same thing on those displays.   That would be really nice.    During the duration of the Mesh Edit screen, I don't think any custom characters are in use.   So it might be possible to use several of them to form the circle and arrow.

@Tannoo   Do you have any comments how this functionality can be replicated on the 20x4 LCD's ?

@thinkyhead  How disruptive is it to merge stuff into bugfix-v1.1.x right now?  I'm guessing we should wait until the new organization can pass Travis and then put this into the new v2.0.0 branch?

2017-09-11 13:37 UTC, marcio-ao commented
@cdedwards: It seems like you are duplicating the graphics I already added to "[dogm_bitmaps.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/dogm_bitmaps.h#L423)". Why don't you use the same bitmaps and simply add an OR clause to the #define so those graphics can be used by either feature? Also, [_lcd_babystep_zoffset_overlay](https://github.com/MarlinFirmware/Marlin/blob/386b74f8c253d912b96064fdeb5250cf665527ca/Marlin/ultralcd.cpp#L1002) could probably be renamed to something more generic and reused.

2017-09-11 14:36 UTC, Roxy-3D commented
I just loaded this and tried it out.  I have a question:    In the middle top of the LCD Panel there is a line.   Some times it has a single dot above it and other times nothing.   Is it supposed to be drawing the nozzle getting closer (or further) from the line?   

With the gMax configuration files...   I'm just getting a dot or no dot.

2017-09-11 14:46 UTC, marcio-ao commented
@Roxy-3D: Since this is based on my original code, let me chime in. My guess is that the following lines need to be moved inside the if statement, after "lcd_implementation_drawedit".

```
#if ENABLED(AUTO_BED_LEVELING_UBL_GFX)
      _lcd_ubl_zoffset_overlay(mesh_edit_value);
#endif
```

2017-09-11 15:06 UTC, Roxy-3D commented
I'm kind of guessing what you are thinking.   Do you mean move the order of the lines to be:
```cpp
      if (lcdDrawUpdate)
        lcd_implementation_drawedit(msg, ftostr43sign(mesh_edit_value));
    }
#if ENABLED(AUTO_BED_LEVELING_UBL_GFX)
      _lcd_ubl_zoffset_overlay(mesh_edit_value);
#endif
```

2017-09-11 15:10 UTC, marcio-ao requested changes
A few suggestions.

2017-09-11 15:10 UTC, marcio-ao commented on Marlin/ultralcd.cpp
> +    #if ENABLED(AUTO_BED_LEVELING_UBL_GFX)
This should use the same graphics as BABYSTEP_ZPROBE_GFX_OVERLAY, as duplicating them would use up a lot of memory. 

Where I have "#if ENABLED(BABYSTEP_ZPROBE_GFX_OVERLAY)", simply use "#if ENABLED(BABYSTEP_ZPROBE_GFX_OVERLAY) || ENABLED(AUTO_BED_LEVELING_UBL)

2017-09-11 15:10 UTC, marcio-ao commented on Marlin/ultralcd.cpp
> +        void _lcd_ubl_zoffset_overlay(float zprobe_zoffset) {
I think this function could be shared between BABYSTEP_ZPROBE_GFX_OVERLAY and AUTO_BED_LEVELING_UBL. Although they would end up sharing a static variable for keeping track of turn direction, it should still work ok as the graphics would be updated as soon as the user started to turn the dial.

2017-09-11 15:10 UTC, marcio-ao commented on Marlin/ultralcd.cpp
> +#if ENABLED(AUTO_BED_LEVELING_UBL_GFX)
This needs to be inside the "if(lcdDrawUpdate)", after "lcd_implementation_drawedit". The reason being that if it isn't, the graphics may be overwritten.

2017-09-11 15:13 UTC, marcio-ao commented
@roxy-3d: No, inside the "if":

```
    if (lcdDrawUpdate)
        lcd_implementation_drawedit(msg, ftostr43sign(mesh_edit_value));
        #if ENABLED(AUTO_BED_LEVELING_UBL_GFX)
           _lcd_ubl_zoffset_overlay(mesh_edit_value); 
        #endif
    }
```

The reason is that "lcd_implementation_drawedit" is what draws the screen and only when that is called we want to update the graphical overlay (which is drawn over the regular screen).

2017-09-11 15:41 UTC, Roxy-3D commented
@marcio-ao    Nope...   Something else will need to be done.

2017-09-11 15:54 UTC, marcio-ao commented
@Roxy-3D: I'm stumped then. Does the BABYSTEP_ZPROBE_GFX_OVERLAY work for you? cdedwards patch is based on that.

2017-09-11 15:56 UTC, Roxy-3D commented
When I go to Z Baby Stepping...  I just have the standard text line.  No graphics there.

2017-09-11 16:00 UTC, marcio-ao commented
@Roxy-3D: Well, you need to enable the following:

- BABYSTEPPING
- BABYSTEP_ZPROBE_OFFSET
- BABYSTEP_ZPROBE_GFX_OVERLAY

In "Configuration_adv.h"

2017-09-11 16:10 UTC, Roxy-3D commented
I don't want the BABYSTEP_ZPROBE_OFFSET enabled....  (I'm using UBL and that option doesn't really make sense there.)    But BABYSTEPPING is turned on, and I just turned on BABYSTEP_ZPROBE_GFX_OVERLAY.    SanityCheck.h complains I need to have BABYSTEP_ZPROBE_OFFSET turned on to use the BABYSTEP_ZPROBE_GFX_OVERLAY option.

I guess you know that!  But that doesn't seem right to me.   It seems like the graphics should be able to show up even if the Z_PROBE_OFFSET_FROM_EXTRUDER number is not being messed with.   (I very much do not want it changed when I use Z-BabyStepping.)

It would seem there shouldn't be separate options.    It would seem to me we should just have one option controlling the Graphics overlays.   Would it make sense to combine AUTO_BED_LEVELING_UBL_GFX and BABYSTEP_ZPROBE_GFX_OVERLAY to control things?

I guess what I'm really asking is does the user need that much configuration granularity?  If they turn on the graphics overlay in one place...  Isn't it very likely they want it everywhere?

2017-09-11 16:18 UTC, marcio-ao commented
@Roxy-3D: Yes, I suggested to @cdedwards that AUTO_BED_LEVELING_UBL_GFX and BABYSTEP_ZPROBE_GFX_OVERLAY should be combined. When I made my PR I was developing for the LulzBot printers, which do not use UBL. I suspect correct way to add support for a graphical overlay to UBL would be to share the code and configuration between the two.

You wouldn't want the overlay everywhere, though. The nozzle graphics only makes sense for operations that involve moving the nozzle up and down.

2017-09-11 16:21 UTC, Roxy-3D commented
> You wouldn't want the overlay everywhere, though. The nozzle graphics only makes sense for operations that involve moving the nozzle up and down.

Right!   But there are number of places where that will help make things more obvious for the user.  G2 P4 is probably the most important.  But G29 P2 (manual probe) would be helpful.   And of course...  The Z-BabyStepping.

2017-09-11 16:33 UTC, marcio-ao commented
@Roxy-3D: I agree. It would be fairly easy to do. The way to do it would be to take the changes I did in PR #7593 and generalize it a bit. "_lcd_babystep_zoffset_" overlay could be renamed something generic such as "_lcd_nozzle_height)adjustment_overlay" or something and then used from within all screens that involve raising or lowering the nozzle.

2017-09-11 16:35 UTC, marcio-ao commented
@Roxy-3D: I suggest integrating PR #7602 first though. @GMagician found a small bug in my PR #7593

2017-09-11 16:39 UTC, Roxy-3D commented
Yeah.  Ok!   Probably what makes sense to do is wait a few days until the v2.0.0 stuff shows up with the new file and folder layout.   And then move all these various changes to that code base.    The problem is merging stuff into bugfix-v1.1.x is disruptive...   And besides that...  It probably gets left behind when the v2.0.0 branch appears.

2017-09-11 16:44 UTC, marcio-ao commented
@Roxy-3D: Does 2.0.0 have any changes other than file location changes? Should I be creating PRs for 2.0 rather than bugfix-v1.1.x?

2017-09-11 16:50 UTC, marcio-ao commented
@Roxy-3D: Although I agree we may want to put off adding the overlay to other screens right now, I would suggest merging PR #7602 as my earlier PR #7593 has *already* been merged, so it's only a bug fix to something that has already been accepted.

2017-09-11 16:50 UTC, Roxy-3D commented
Pretty much...  v2.0.0 is a version of bugfix-v1.1.x frozen a 4 or 5 days ago.   

The only changes in v2.0.0 should be what it takes to break apart the code base into smaller modules and put those files into their own folders.     You know how reliable software schedules are.   But supposedly in a few days we should be able to start using and doing Pull Requests against v2.0.0

So...  in my opinion...   The answer is "Yes...   we should be doing Pull Requests against v2.0.0 but the problem is it isn't fully baked yet and we don't really want to merge anything new into yet anyway."

2017-09-11 16:53 UTC, Roxy-3D commented
> I would suggest merging PR #7602 as my earlier PR #7593 has already been merged,

Yes...   I understand.   But I think what is going to happen is that Pull Request will get re-based against the v2.0.0 code when it shows up in the next week.   I'm not positive about this, but I think Thinky wants bugfix-v1.1.0 to stay frozen until that happens.

2017-09-11 16:54 UTC, marcio-ao commented
@Roxy-3D: Ah. Okay. I'll be patient then :)

2017-09-11 16:59 UTC, Roxy-3D commented
Don't worry...   It will happen!   But we are in kind of an awkward transition phase right now.

2017-09-11 23:07 UTC, cdedwards commented
I agree the code should be shared.. when I attempted that however, it was not finding the graphic char arrays, so I went a different route for now. The overlay function, and the graphics should be made slightly more generic and then can be used in several different places where the nozzle and bed are changing, UBL is just one example. When 2.0 is released I will take another stab at this, or leave it in your capable hands.

2017-09-12 05:03 UTC, Roxy-3D commented
> When 2.0 is released I will take another stab at this, or leave it in your capable hands.

We can work on this now...  And when v2.0.0 shows up...  It can be the first merge to the new branch.
And in fact...   I would argue...  We can just keep modifying this Pull Request to make it 'correct' with everybody agreeing to the feature set.

Everybody (myself included) is learning from this.   Let's just plow ahead and make sure everybody's ideas are addressed.

2017-09-12 19:46 UTC, marcio-ao commented
@cdedwards: I think you are on the right track. The reason you probably were not finding the graphics is that you need to replace "#if ENABLED(BABYSTEP_ZPROBE_GFX_OVERLAY)" with "#if ENABLED(BABYSTEP_ZPROBE_GFX_OVERLAY) || ENABLED(AUTO_BED_LEVELING_UBL)" in "Marlin/dogm_bitmaps.h" so that way the graphics will be loaded if either BABYSTEP_ZPROBE_GFX_OVERLAY *or* AUTO_BED_LEVELING_UBL are defined.

2017-09-12 20:00 UTC, marcio-ao commented
@roxy-3d: Not sure why the nozzle graphics isn't showing up for you. That remains a mystery to me. But the line in the code that draws that bitmap is the following:

 if(PAGE_CONTAINS(3,16))  u8g.drawBitmapP(nozzle + 6, 4 - dir,2,12,nozzle_ubl_bmp);

You could try a couple things. Replace that line with:

u8g.drawBitmapP(nozzle + 6, 4 - dir,2,12,nozzle_ubl_bmp);

The PAGE_CONTAINS(...) is an optimization, but you can see if it works without it. If that doesn't work, try this:

u8g.drawBitmapP(nozzle + 6, 4,2,12,nozzle_ubl_bmp);

The "dir" variable is what nudges the nozzle up and down. The value should be either 1 or -1, depending on which direction the value is chaning, but if for some reasons it is not, the above test will reveal it (by drawing the graphics at a fixed location of 4).

2017-09-12 20:15 UTC, marcio-ao commented
@Roxy-3D: The following page explains how graphics are drawn and was helpful to me in understanding how Marlin drawing graphics:

https://github.com/olikraus/u8glib/wiki/tpictureloop

It turns out that draw function is actually called multiple times, in a loop, for different "pages" of the screen. The PAGE_CONTAINS(y1,y2) macro checks to see whether Marlin is drawing rows y1 through y2. The arguments to are u8g.drawBitmapP(x,y,bytes_across,rows_down,bmp), so the following line:

if(PAGE_CONTAINS(3,16)) u8g.drawBitmapP(nozzle + 6, 4 - dir,2,12,nozzle_ubl_bmp);

Means:

If rows 3 through 16 are in the page which is being drawn, then draw the bitmap 2 bytes wide and 12 rows tall at (x,y) = (nozzle+6, 4 - dir).

The fact that you are seeing a dot at the top of the screen makes me suspect that the bitmap isn't being drawn at the correct location. You can try modifying the first two parameters of drawBitmapP to see if you can get it to show up.

2017-09-15 03:39 UTC, Tannoo commented
@Roxy-3D, I have not looked at this yet. Been busy with life atm. I want to apply this to the 2.0.0 and try it. It sounds like a wonderful addition. Still a few days from now.

2017-09-20 03:04 UTC, Tannoo commented
>I would suggest merging PR #7602 as my earlier PR #7593 has already been merged...

I have included these two PR's into my bugfix-2.0.x and had some errors about the bitmaps not being defined. Well, I defined them and now have wierd lines as if the bitmaps are not interlaced correctly.

I am trying to get this to work before looking into the 20x4.

2017-09-21 01:44 UTC, cdedwards commented
I'm attempting to implement this on the refactor version of 2.0. currently stuck at 

linking .pioenvs\Re-ARM\firmware.elf
.pioenvs/Re-ARM/src/src/lcd/ultralcd.o: In function `U8GLIB::U8GLIB(_u8g_dev_t*, unsigned char, unsigned char, unsigned char)':
I:\GitHub\Marlin/.piolibdeps\U8glib-ARM_ID1691\src/U8glib.h:73: undefined reference to `U8GLIB::initHWSPI(_u8g_dev_t*, unsigned char, unsigned char, unsigned char)'
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\Re-ARM\firmware.elf] Error 1
 [ERROR] Took 13.19 seconds

I've had to specifically enable DOGLCD in my configuration.h.  As far as I can see this is defined in u8glib.h

 /* constructor */
    U8GLIB(void)
      { }
    U8GLIB(u8g_dev_t *dev)
      { prepare(); u8g_Init(&u8g, dev); }
    U8GLIB(u8g_dev_t *dev, u8g_com_fnptr com_fn)
      { prepare(); u8g_InitComFn(&u8g, dev, com_fn); }
    U8GLIB(u8g_dev_t *dev, uint8_t sck, uint8_t mosi, uint8_t cs, uint8_t a0, uint8_t reset) 
      { initSPI(dev, sck, mosi, cs, a0, reset); }
    U8GLIB(u8g_dev_t *dev, uint8_t cs, uint8_t a0, uint8_t reset) 
      { initHWSPI(dev, cs, a0, reset); }

2017-09-21 01:47 UTC, cdedwards commented
as for the missing char maps, need to move the HAS_TEMP_BED in the dogm_bitmaps.h

that was what was causing the issue for my attempt at adding this to ubl.

2017-09-21 23:11 UTC, Tannoo commented
Is this PR updated with the latest that works?

2017-09-21 23:45 UTC, cdedwards commented
no it isn't. since it's possible to combine the two so there is only one set of functions.

2017-09-24 23:28 UTC, closed without merging