z_offset
MarlinFirmware/Marlin pull request #8423
Opened 2017-11-14 11:47 UTC by LVD-AC

2017-11-14 11:48 UTC, LVD-AC commented
Fix for #8380

2017-11-14 12:25 UTC, LVD-AC commented
Debugging has become a real pain with the Arduino IDE no longer compiling and that U8glib.h missing in 2.0.x

2017-11-14 14:18 UTC, fiveangle commented
Arduino 1.9 beta works around cmd  length limit in Windows and what do you mean no U8glib ?

2017-11-14 14:47 UTC, LVD-AC commented
```
sketch\src\lcd\dogm\u8g_dev_ssd1306_sh1106_128x64_I2C.cpp:72:20: fatal error: U8glib.h: No such file or directory

 #include <U8glib.h>
```
That's what I'm getting; I think I just have to sit this one out until the problem is solved...

2017-11-14 14:57 UTC, LVD-AC commented
@fiveangle I did try 1.1.9 beta; it got rid of the U8glib.h error but still does not compile due to cmd length error. So I rolled back to 1.1.8.

2017-11-14 17:53 UTC, fiveangle commented
I highly suggest to communicate your finding with Arduino as they beleive there is no issue : https://github.com/arduino/Arduino/issues/6751

2017-11-14 21:31 UTC, cdedwards commented
something else to try is removing the .piolibsdep directory. will force atom/arduiono to redownload all the lib files.

2017-11-14 22:30 UTC, stuartmp commented
Try using AtmelStudio with the visual micro plugin it work so much better the the standard arduino IDE

[http://www.atmel.com/microsite/atmel-studio/](url)
[http://www.visualmicro.com/](url)

2017-11-15 05:49 UTC, LVD-AC commented
@stuartmp yet another software to learn; I'm afraid if 2.0 does not compile on Arduino a lot of people just will not use it. This needs to be solved
@fiveangle the trouble I have is `U8glib.h: No such file`, until recently there was no problem here; is this related to that command line problem that I do not have in 1.1.8
@cdedwards `.piolibsdep directory` ??? Where can I find it, I do not seem to have one. I did a completely fresh install on Monday so I would have an Arduino like any newbe would have, did not change any settings or preferences from the defaults.

2017-11-15 06:11 UTC, fiveangle commented
I can compile 2.0 with U8glib.h without issue.  If you want to hit me with the exact code, I can hit it and see if I get the same error.

2017-11-15 07:42 UTC, benlye commented
I can compile bugfix-2.0.x as well in Arduino IDE.  

@LVD-AC, forgive the stupid question, but did you reinstall the U8glib using Library Manager after reinstalling the IDE?  I found on my systems that sometimes it gets removed during upgrades/re-installs.

2017-11-15 08:21 UTC, thinkyhead commented on Marlin/src/core/utility.cpp
> +    SERIAL_ECHOLNPGM(" Nozzle)");
Pretty sure this doesn't need to be displayed to users who have no probe.

2017-11-15 08:24 UTC, thinkyhead requested changes
I'm leaning towards rejecting this, as it balloons the code size for users with no probe, with no added benefit. If you have no probe, there should be no `zprobe_zoffset` and no `M851` command.

2017-11-15 11:02 UTC, stuartmp commented
Me too. Try reinstalling the latest version of the library again from within the arduino IDE.

On 15 November 2017 5:42:23 PM AEST, Ben Lye <notifications@github.com> wrote:
>I can compile bugfix-2.0.x as well in Arduino IDE.  
>
>@LVD-AC, forgive the stupid question, but did you reinstall the U8glib
>using Library Manager after reinstalling the IDE?  I found on my
>systems that sometimes it gets removed during upgrades/re-installs.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/pull/8423#issuecomment-344510829

-- 
Sent from my Android device

2017-11-15 11:35 UTC, LVD-AC commented
@thinkyhead, maybe useless on Cartesians, but quite useful on Delta's. Calibrating a delta printer with papertests is using the nozzle as a (non automated) probe. By definition X and Y offsets are forced to zero, but a Z component that is adjustable is extremely useful to set the right print height for the 1st layer.

I could restrict this PR only to Deltas if you like.

2017-11-15 11:37 UTC, LVD-AC commented
@benlye no, I never installed a library myself, Arduino used to take care of that.

2017-11-15 12:09 UTC, benlye commented
> Is that U8glib by Oliver?

Yes. This is it:
![image](https://user-images.githubusercontent.com/23322579/32835367-1804cffa-ca06-11e7-823f-3b0c413dbec8.png)

2017-11-15 13:05 UTC, LVD-AC commented
@benlye 👍 That was it; strange that Bugfix-1.1.x compiled without it. But now I got
```
fork/exec C:\Users\Luc\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-gcc.exe: The filename or extension is too long.```

2017-11-15 13:18 UTC, benlye commented
Ah, now you have the famous command-line-too-long problem and you need to switch to the 1.9.0 beta IDE.

2017-11-15 16:53 UTC, cdedwards commented
or you can set an environment variable and it will work fine... set TMP=C:\TMP and set TEMP=c:\TMP  will fix the compile issue

2017-11-15 17:06 UTC, LVD-AC commented
@thinkyhead updates as in 1.1.x

2017-11-15 17:20 UTC, LVD-AC commented
@cdedwards that worked 👍

2017-11-16 11:15 UTC, LVD-AC commented
For Delta users it makes sense; delta's do not have M206, they rely on M851 to tweak the print height of the 1st layer (probe or no probe). So that is what this PR does, it enables M851 and the LCD-menu for delta's without a probe. (tested and it works as expected)

2017-11-18 12:37 UTC, closed without merging

2017-11-26 02:56 UTC, thinkyhead commented
> Calibrating a delta printer with papertests is using the nozzle as a (non automated) probe.

Ah, well it does make sense in that sort of case. It should be "packaged" in some way that doesn't refer to "the probe" but uses language referring to the "gap" or "feeler gauge" when doing manual bed leveling.

2017-11-26 10:36 UTC, LVD-AC commented
See my comment in #8479 - for the time being I'll make G33 to have it's own G33_z_offset so it can continue to function; and if and when a universal zprobe_zoffset solution is found it can be dropped again for consistency.

2017-11-26 10:46 UTC, stuartmp commented
Why not just make a new control variable that describes this functionality. Something like Z_Bed_Nozzle_Offest. This gets rid of the word probe and describes what the offset is intended for.

2017-11-26 16:35 UTC, LVD-AC commented
I was doing something of a sort (named it additional_z_offset; usage for the time being limited to G33, but...)
See #8571 and #8572

2018-01-26 21:42 UTC, thinkyhead commented
> Why not just make a new control variable that describes this functionality.

That pretty much duplicates the behavior of `home_offset[Z]`, but adds yet another variable to the system. The thing is, if we're seeing a general inaccuracy across the whole bed, it will be due to one of the following causes:
- Z endstop inaccuracy
- Probe Z offset inaccuracy
- Probe Z offset flexibility, as with moody inductive probes
- Bed/nozzle distance changes after bed/nozzle heat up

So we have babystepping, and will certainly always need babystepping, to dial in the first layer as the print is starting out.

If a user sees that he always has to babystep by the same amount, he can investigate further, adjust the value that is inaccurate, turn the screw that moves the Z endstop, etc. The conceit of `BABYSTEP_ZPROBE_OFFSET` is to assume the Z probe offset is the weak link. But this will not always be the case, so always applying babystepping to any specific setting could lead to side-effects elsewhere.

The best solution, really, if a user finds he must babystep a lot after `M420 S1` but never after `G29` is to just stop using saved meshes and always re-generate them with `G29`. The `G29` procedure will compensate for any current distance-to-bed inaccuracy in a way that `M420 S1` can't do.

Maybe all you need to allow for changing conditions is to do a single probe to check the bed center hasn't changed, and just adjust up and down based on that single probe reading. This assumes the probe-to-nozzle distance can't change. But, alas, with inductive probes, that actually becomes an unreliable value too.