[1.1.x] G33 kinematic auto tune factors
MarlinFirmware/Marlin pull request #8821
Opened 2017-12-17 12:03 UTC by LVD-AC

•updated convergence matrices
•kinematic auto tune scaling parameters
•raw calibration independent of Z-offset
•Z-offset calibration with G33 P-1 and G33 Zn.nn

2017-12-25 10:53 UTC, thinkyhead commented on Marlin/Marlin.h
> +extern float zprobe_zoffset;
This should not be defined all the time.

2017-12-25 10:53 UTC, thinkyhead requested changes

2017-12-25 10:53 UTC, thinkyhead commented on Marlin/Marlin.h
> +extern float zprobe_zoffset;
This should not be defined all the time.

2018-01-12 02:32 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +      do_homing_move(axis, delta_endstop_adj[axis] - MIN_STEPS_PER_SEGMENT / planner.axis_steps_per_mm[axis] * Z_HOME_DIR);
Clever maths. I like.

2018-01-12 02:35 UTC, thinkyhead approved these changes

2018-01-12 04:06 UTC, thinkyhead commented
Reviewing this now. You've cajoled me into it!

Just kidding. I finally have time to get into this stuff over the next few days. Let's get this to a happy place for all the delta kiddies out there.

2018-01-22 02:45 UTC, thinkyhead commented on Marlin/configuration_store.cpp
> -    EEPROM_WRITE(zprobe_zoffset);
I'm confused. Why change the condition that creates a dummy `zprobe_zoffset` but then not write it to EEPROM?

2018-01-22 02:47 UTC, thinkyhead commented on Marlin/configuration_store.cpp
> -      EEPROM_READ(zprobe_zoffset);
I'm confused. Why change the condition that creates a dummy `zprobe_zoffset` but then not read it from EEPROM?

What's the bigger picture here? Why should we not save `zprobe_zoffset` to EEPROM anymore for all configurations?

2018-02-26 15:04 UTC, LVD-AC commented
"These conflicts are to complex to resolve in the web editor"

I guess this one died of old age

2018-02-27 02:43 UTC, thinkyhead commented
I'll resolve them using the tools of the trade. Hold on…

2018-02-27 02:47 UTC, thinkyhead commented
Wow, that was surprisingly easy. No conflicts on rebase!

2018-02-27 03:23 UTC, thinkyhead commented
I've split out the example config changes and extra language changes into separate commits so it's easier to see the important changes by looking at the first commit.
```sh
git diff HEAD HEAD~1 | git apply     ;# UNDO all files to before original commit
                                      # (Github Desktop: Commit undo of just configs and languages)
git reset --hard HEAD                ;# throw away uncommitted changes
git diff HEAD HEAD~1 | git apply     ;# revert files to the original commit's state
                                      # (Github Desktop: Commit example config changes)
                                      # (Github Desktop: Commit language changes)
git rebase -i upstream/bugfix-1.1.x  ;# Let's squash commits!
                                      # (JOE: Combine the undo with the original commit)
git push -f LVD-AC HEAD:kinematic-auto-tune-1.1.7
```

2018-03-01 00:17 UTC, thinkyhead commented
`M212` — Agreed! This is more standard. We'll have to retain `M851` for legacy reasons. It will be simple enough. It would just subtract `Z_PROBE_OFFSET_FROM_EXTRUDER` from the given `Z` parameter and then do the same thing as `M212`.

2018-03-01 10:54 UTC, LVD-AC commented
2 G-codes to set the new variable offset:

M212 = M851 - Z_PROBE_OFFSET_FROM_EXTRUDER right?

easy enough...

2018-03-02 10:20 UTC, thinkyhead commented
I've been going over this PR tonight and will get back into it more tomorrow. I hope to find the means to integrate this functionality with the least conceptual disruption (paradigm shift), and will aim for getting that done in the next 2-3 days. I do think this is cleaner than re-introducing the `home_offset`.

I checked the printrbot fork, and `M212` is actually a complete synonym for `M851` (but it also supports X and Y offsets). Although the reprap wiki refers to it as an "offset to home," printrbot specifically refers to the probe that moves with the hotend, and in answers to user questions they refer to it as the "probe-to-nozzle distance" as opposed to a "home offset."

That isn't to say that we can't pick another code or add an extra parameter to accomplish what `M212` is doing in this PR, but it demonstrates that the probe-nozzle relationship is fundamental to much of the thinking around these kinds of adjustments. So we do need to retain functions that specifically relate to adjusting that distance.

Anyway, it's been a long night, so I'll get back into this later.

2018-03-02 13:41 UTC, LVD-AC commented
What you say is valid only for people that have a probe. What this PR does it enables babystepping and a G-code command with which people can change the print-height of the 1st layer without disturbing calibration and level data **on all printers**. M851 and M212 are quit synonym indeed. The difference lies IMO that M851 is probe related and a s such you need a probe on your printer to have access to that command, while M212 is general for all printers.

As you will see I only enabled M851 for printers that home with a probe; and enabled M212 for all. I've chosen that option because for legacy reasons that functionality in 1.1.8 only works properly on printers that home with a probe. It used to work as well on deltas with a probe, but that was abandoned so I'm not gonna get into it, water under the bridge. And in my opinion even if you set the offset of the probe, having an additional offset to that independent of the probe might be preferred to some users, and if not... wel just ignore M212 exists.

But if you feel M851 should be enabled on all printers that have a probe, be my guest just change the #if statements (it does exactly the same thing as M212 so there will be no problems).

Just as if you prefer to restrict M212 to printers that do not have a probe; that is just adding a couple of #if's to M212

I leave these decisions up to you; as long as all printer have at least one G-code I'm a happy bunny. (personally I prefer 212, it's an easier number to remember).

2018-03-02 14:00 UTC, LVD-AC commented
Another option is off course to give all printers access to M851 (as this it the legacy command in Marlin) and forget about M212 all to getter.

I see it as if all printers do have a probe, some have an automated probe that generates an electrical signal when triggered, but those who do not have that use the nozzle in papertests to determine the height to set up their printer. So nozzle-to-probe offset could as well be inclusive to nozzle-to-papertest offset. **M851 for all** is my preferred option for all, since we all need to probe bed one way or another; the probing mechanisms we use quit differ, but dealing with them in the exactly the same way makes it less complicated to explain and understand. Bl-touch, allen key switch, nozzle switch, papertest, whatever... you can babystep or use M851 to tweak the height of your 1st layer. (and it does not mess up previous obtained calibration and bed level data).

2018-03-03 21:56 UTC, thinkyhead commented
> I see it as if all printers do have a probe…

Yes! I totally agree, which is how `PROBE_MANUALLY` became a "probe."

2018-03-09 09:31 UTC, thinkyhead commented
Rebased this 4 u.

To make this easier to evaluate, I've created a copy where I've reverted all the renaming to "supplemental" with the aim of (1) concealing the usage of "supplemental offset" from the user, (2) incorporating the functionality in a more explicit fashion ("You are now adjusting height and probe offset in conjunction"), and (3) eliminating the treatment of `Z_PROBE_OFFSET_FROM_EXTRUDER` as having any meaningful significance — since users should be free to set this to zero in their configuration and just use `M851` if that is their choice.

From this starting-point I hope to rework the code into a form that accomplishes exactly what this does, but without the seismic shift that this PR imposes. I'll aim to get that done over the next couple of days.

2018-04-03 09:18 UTC, LVD-AC commented
Split into #9310 for z-offset and #8821 for G33 improuvements

2018-04-11 22:53 UTC, thinkyhead commented on Marlin/Marlin_main.cpp
> +      do_homing_move(axis, delta_endstop_adj[axis] - MIN_STEPS_PER_SEGMENT / planner.axis_steps_per_mm[axis] * Z_HOME_DIR);
Note that it's perfectly legal to have `MIN_STEPS_PER_SEGMENT` set to 0.

2018-04-11 23:03 UTC, thinkyhead commented
Ok, this seems good! I will merge it shortly. Please make a PR with all the same changes for `bugfix-2.0.x` so everything is in sync.

2018-04-11 23:38 UTC, LVD-AC commented
Done: see #8822

2018-04-11 23:47 UTC, LVD-AC commented
Seems my french side takes over whenever I write centre. LOL

2018-04-11 23:51 UTC, thinkyhead commented
Ok, just so I'm clear on this… Oui to #10362 and #10363. No special handling for `G33` needed?

2018-04-12 00:00 UTC, LVD-AC commented
I see no problems with users setting their own probe depth. G33 S(etup) avoids bowl-shapes so no problems there.

2018-04-12 00:12 UTC, merged