[2.0.x] Improved Pause/Load/Unload, M701-M702
MarlinFirmware/Marlin pull request #9042
Opened 2018-01-04 05:53 UTC by thinkyhead

Based on #7107 by @tcm0116 

- Adds `M701` / `M702` general codes to load and unload filament.
- MK2 multiplexer (SNMM) is supported via `tool_change`.

2018-01-04 16:08 UTC, petrzjunior commented
Wow, good job @tcm0116 and @thinkyhead! Can't wait to test it.

2018-01-04 17:30 UTC, tcm0116 requested changes

2018-01-04 17:30 UTC, tcm0116 commented on Marlin/src/feature/pause.h
> +static bool unload_filament(const float &unload_length, const bool show_lcd=false, const AdvancedPauseMode mode=ADVANCED_PAUSE_MODE_PAUSE_PRINT);
`load_filament` and `unload_filament` shouldn't be declared as `static`.

2018-01-04 17:30 UTC, tcm0116 commented on Marlin/src/feature/pause.cpp
> +static bool load_filament(const float &load_length/*=0*/, const float &extrude_length/*=0*/, const int8_t max_beep_count/*=0*/,
`load_filament` shouldn't be declared as `static`.

2018-01-04 17:30 UTC, tcm0116 commented on Marlin/src/feature/pause.cpp
> +static bool unload_filament(const float &unload_length, const bool show_lcd/*=false*/,
`unload_filament` shouldn't be declared as `static`.

2018-01-04 21:08 UTC, thinkyhead commented
@petrzjunior — Have you been using the `bugfix-2.0.x` branch? This stuff is already merged into `bugfix-1.1.x` and should be ready to go.

2018-01-05 01:41 UTC, merged

2018-01-05 02:18 UTC, tcm0116 commented
Awesome! Thanks for porting this over!