M73 Enhancements
MarlinFirmware/Marlin pull request #9208
Opened 2018-01-16 19:33 UTC by benlye

* Allow LCD_SET_PROGRESS_MANUALLY to be enabled without SDSUPPORT
* Add T parameter to set the time elapsed

2018-01-16 19:41 UTC, benlye commented
I think it's worth mentioning that I had to constrain the T parameter to 1sec less than 100 days because setting a value of 100 days or greater caused Marlin to reset.  This is, I think, a bug in the way time values with days are rendered on the LCD.

Also, with `DOGM_SD_PERCENT` enabled, any value with days displays incorrectly.  For example, 50% with a time of 1 day 12:34 displays as `50% 1d 12:3`.  A time with 10 days displays as `50%10d 12:3`.  I suspect the problem is in [https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/libs/duration_t.h#L151-L155](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/libs/duration_t.h#L151-L155).

Unless someone else gets there first I'll try to figure out what those problems are.

2018-01-17 01:07 UTC, dot-bob commented
I wonder if we should also add reporting print percentage using the firmware capabilities protocol as well: [http://www.reprap.org/wiki/Firmware_Capabilities_Protocol](http://www.reprap.org/wiki/Firmware_Capabilities_Protocol)

2018-01-17 09:30 UTC, benlye commented
Rebased to take #9202 into account.

2018-01-17 10:53 UTC, benlye commented
Travis seems to have been broken by https://github.com/MarlinFirmware/Marlin/commit/acb1e313746c721c470e8e045bdd98446b4c58c7.

#9214

2018-01-17 18:29 UTC, benlye commented
This isn't ready yet.  

I just realized that it will prevent a running printjob_timer from updating the screen.  In truth, I wasn't aware of the way printjob_timer worked, and it largely provides the functionality I was aiming for with the `M73 T` parameter.  

I think that it might still be useful though so I'll attempt to make it co-exist with printjob_timer by only taking updates if there is no timer running.

2018-01-18 09:45 UTC, benlye commented
I've now added a separate option for manual control of the progress bar timer, `LCD_SET_TIMER_MANUALLY`.  It is dependent on `LCD_SET_PROGRESS_MANUALLY`.

This solves the problem I created where print_job_timer was being ignored if 
 `LCD_SET_PROGRESS_MANUALLY` was enabled but timer updates weren't sent from the host.

It works as expected for me.  With `LCD_SET_PROGRESS_MANUALLY` I can manually control the progress bar with `M73` and print_job_timer is in control of the timer.  With `LCD_SET_PROGRESS_MANUALLY` and `LCD_SET_TIMER_MANUALLY` enabled print_job_timer has no effect on the display and manual updates are done via `M73 T`.

It may not be terribly useful to have manual control over the timer, but it was interesting to use `M73 T` commands to find a couple of bugs (#9202, #9220).  There is one more lurking, where Marlin resets if the timer exceeds 100 days (unlikely, I know).

Removing the `SDSUPPORT` dependency for `LCD_SET_PROGRESS_MANUALLY` is much more interesting to me and if no one wants `LCD_SET_TIMER_MANUALLY` I'd be happy to do a new PR just to change that.

2018-01-24 07:28 UTC, thinkyhead requested changes
The way this feature is structured, it fully disables the use of the print job's built-in timer, even though the timer still runs. It would be better to move `elapsed` into the `Stopwatch` class and:

- Add methods to set and clear the `elapsed` value
- Modify `Stopwatch` so `duration` returns `elapsed` when it's non-zero, otherwise the usual value. Since `Stopwatch` uses `duration` internally, rename it `_duration` and make a new `duration` method (that calls `_duration`) for the rest of Marlin to use.

Also, these features should be enabled for character LCD too. The code is almost the same.

2018-01-24 07:28 UTC, thinkyhead commented on Marlin/Configuration_adv.h
> +  //#define LCD_SET_PROGRESS_MANUALLY
The character LCD also displays a progress percentage.

2018-01-25 08:52 UTC, benlye commented
@thinkyhead, the changes you're asking for make sense, but are beyond what I can do at the moment.

I've re-scoped this PR to just do the one thing I really wanted - allow M73 without SDSUPPORT.  I've stashed the other changes so I can pick that up again another day.

2018-02-17 13:49 UTC, thinkyhead approved these changes

2018-02-17 21:50 UTC, merged

2018-02-21 14:31 UTC, Zer0t3ch commented
Looks like this currently only functions with full graphics LCDs, but it should work with others. (I've had a functional progress bar with my "ZONESTAR_LCD" in the past)

2018-02-23 08:23 UTC, thinkyhead commented
@Zer0t3ch — Do you have `LCD_PROGRESS_BAR` enabled? Try the current bugfix branch and see if there's a visible progress bar when that option is enabled, and check whether you can change it with `M73` when `LCD_SET_PROGRESS_MANUALLY` is enabled without `SDSUPPORT`.

2018-02-23 16:24 UTC, Zer0t3ch commented
@thinkyhead I'm on the Bugfix-v2 branch, and it won't compile for me at all with both `LCD_PROGRESS_BAR` and `LCD_SED_PROGRESS_MANUALLY` enabled. I believe this is because the progress bar timing is undefined, the timing is still declared inside an `if SDSUPPORT` block.

Here's the tail-end of my output:

```
In file included from /home/pi/marlin/build/sketch/src/lcd/ultralcd.cpp:115:0:
/home/pi/marlin/build/sketch/src/lcd/ultralcd_impl_HD44780.h: In function 'void lcd_set_custom_characters(uint8_t)':
/home/pi/marlin/build/sketch/src/lcd/ultralcd_impl_HD44780.h:432:51: error: 'progress' was not declared in this scope
                 createChar_P(LCD_STR_PROGRESS[i], progress[i]);
                                                   ^
In file included from /home/pi/marlin/build/sketch/src/lcd/../inc/MarlinConfigPre.h:27:0,
                 from /home/pi/marlin/build/sketch/src/lcd/ultralcd.cpp:23:
/home/pi/marlin/build/sketch/src/lcd/ultralcd_impl_HD44780.h: In function 'void lcd_implementation_status_screen()':
/home/pi/marlin/build/sketch/src/lcd/ultralcd_impl_HD44780.h:895:74: error: 'PROGRESS_BAR_MSG_TIME' was not declared in this scope
     if (progress_bar_percent > 2 && (ELAPSED(millis(), progress_bar_ms + PROGRESS_BAR_MSG_TIME) || !lcd_status_message[0]))
                                                                          ^
/home/pi/marlin/build/sketch/src/lcd/../inc/../core/macros.h:189:40: note: in definition of macro 'PENDING'
 #define PENDING(NOW,SOON) ((long)(NOW-(SOON))<0)
                                        ^
/home/pi/marlin/build/sketch/src/lcd/ultralcd_impl_HD44780.h:895:38: note: in expansion of macro 'ELAPSED'
     if (progress_bar_percent > 2 && (ELAPSED(millis(), progress_bar_ms + PROGRESS_BAR_MSG_TIME) || !lcd_status_message[0]))
                                      ^
/home/pi/marlin/build/sketch/src/lcd/ultralcd.cpp: In function 'void lcd_status_screen()':
/home/pi/marlin/build/sketch/src/lcd/ultralcd.cpp:680:41: error: 'PROGRESS_BAR_MSG_TIME' was not declared in this scope
       if (ELAPSED(ms, progress_bar_ms + PROGRESS_BAR_MSG_TIME + PROGRESS_BAR_BAR_TIME))
                                         ^
/home/pi/marlin/build/sketch/src/lcd/../inc/../core/macros.h:189:40: note: in definition of macro 'PENDING'
 #define PENDING(NOW,SOON) ((long)(NOW-(SOON))<0)
                                        ^
/home/pi/marlin/build/sketch/src/lcd/ultralcd.cpp:680:11: note: in expansion of macro 'ELAPSED'
       if (ELAPSED(ms, progress_bar_ms + PROGRESS_BAR_MSG_TIME + PROGRESS_BAR_BAR_TIME))
           ^
/home/pi/marlin/build/sketch/src/lcd/ultralcd.cpp:680:65: error: 'PROGRESS_BAR_BAR_TIME' was not declared in this scope
       if (ELAPSED(ms, progress_bar_ms + PROGRESS_BAR_MSG_TIME + PROGRESS_BAR_BAR_TIME))
                                                                 ^
/home/pi/marlin/build/sketch/src/lcd/../inc/../core/macros.h:189:40: note: in definition of macro 'PENDING'
 #define PENDING(NOW,SOON) ((long)(NOW-(SOON))<0)
                                        ^
/home/pi/marlin/build/sketch/src/lcd/ultralcd.cpp:680:11: note: in expansion of macro 'ELAPSED'
       if (ELAPSED(ms, progress_bar_ms + PROGRESS_BAR_MSG_TIME + PROGRESS_BAR_BAR_TIME))
           ^
Using library LiquidCrystal at version 1.0.7 in folder: /home/pi/marlin/arduino/libraries/LiquidCrystal
exit status 1
```

2018-02-23 19:52 UTC, thinkyhead commented
Your `Configuration_adv.h` is screwy if `PROGRESS_BAR_MSG_TIME` and `PROGRESS_BAR_BAR_TIME` aren't defined when `LCD_PROGRESS_BAR` is defined. It should look like this:
```cpp
  // Show a progress bar on HD44780 LCDs for SD printing
  //#define LCD_PROGRESS_BAR

  #if ENABLED(LCD_PROGRESS_BAR)
    // Amount of time (ms) to show the bar
    #define PROGRESS_BAR_BAR_TIME 2000
    // Amount of time (ms) to show the status message
    #define PROGRESS_BAR_MSG_TIME 3000
    // Amount of time (ms) to retain the status message (0=forever)
    #define PROGRESS_MSG_EXPIRE   0
    // Enable this to show messages for MSG_TIME then hide them
    //#define PROGRESS_MSG_ONCE
    // Add a menu item to test the progress bar:
    //#define LCD_PROGRESS_BAR_TEST
  #endif
```

2018-02-23 20:05 UTC, thinkyhead commented
Aha, yes. You nailed it. That is now fixed.

2018-02-24 00:05 UTC, Zer0t3ch commented
@thinkyhead Glad I could help but I'm still having an issue. Normally I wouldn't ask here, but I think it's relevant. 

Somehow, enabling `LCD_SET_PROGRESS_MANUALLY` (and `LCD_PROGRESS_BAR`, as sanity check fails without it) is causing compilation for me to fail, like this:

```
In file included from /home/zac/marlin/build/sketch/src/lcd/ultralcd.cpp:115:0:
/home/zac/marlin/build/sketch/src/lcd/ultralcd_impl_HD44780.h: In function 'void lcd_set_custom_characters(uint8_t)':
/home/zac/marlin/build/sketch/src/lcd/ultralcd_impl_HD44780.h:432:51: error: 'progress' was not declared in this scope
                 createChar_P(LCD_STR_PROGRESS[i], progress[i]);
                                                   ^
Using library LiquidCrystal at version 1.0.7 in folder: /home/zac/marlin/arduino/libraries/LiquidCrystal
exit status 1
```
On a sidenote, have a look at [this](https://github.com/MarlinFirmware/Marlin/commit/e65a853c59de71c5bb2d61dd15a6024f98060342#r27755423) suggestion I made in regards to your commit. (dunno if you get notifications for that stuff)

2018-02-24 00:32 UTC, Zer0t3ch commented
http://paste.ubuntu.com/p/7yQ3tqQvxC

That diff fixes it. It seems the the block declaring the `progress`  array(?) was still inside an `if SDSUPPORT` block. Moving it outside works without issue.

2018-02-24 00:54 UTC, thinkyhead commented
Thanks! In terms of code organization, things are only going to get better and less scattered around.

2018-02-24 00:59 UTC, Zer0t3ch commented
Yep, I can already tell. The 2.0 branch looks loads more organized in file structure, alone. I can't wait to see what the future holds for this project.